#+TITLE: Принуждение анкап vs анком

/В предыдущих сериях/: *[[file:socialism.org][Социализм - база]]*

-----

Большая часть капиталистов не анкапы и большая часть социалистов не анкомы, но в чате Солнечной Империи все так или иначе упирается в эту дихотомию, и в этом контексте я набрала большую часть своих патронов. Поэтому дискурс в этой ветке будет выглядеть несколько... маргинальным, битва между самыми крайними, гиперболизированными проявлениями идеологий. Но даже когда речь идет о серых зонах, эти предположения все равно составляют базу для условно-правых и условно-левых взглядов на мир, так что пусть так.

Что анкапы, что анкомы не очень любят принуждение и насилие, но они преследуют фундаментально разные подходы к их уменьшению. Если говорить просто, анкапы уменьшают принуждение другим принуждением, а анкомы избавляются от стимулов принуждать.

В (анархо-)капитализме предполагается, что ты принуждаешь тех, кто принуждает, клин клином. Если кто-то нарушает твои права, накажи их. Выдай всем пистолеты для самозащиты. Если арендатор не платит аренду, абсолютно вызови на него полицию, которая угрозами оружием выпнет его из дома. Если Карл украл у меня кораллы, я иду и забираю их обратно, даже если я для этого использую больше силы, чем использовал Карл. Цивилизация это комната с хорошо вооруженными джентльменами.

Это может работать на индивидуальном уровне – на меня нападает грабитель, но я стреляю первая – так и на уровне коллективных систем – защитные агентства, полиция, тюрьмы и прочие структуры, которые могут применять насилие систематизированным образом с целью уменьшить его в обществе в целом. В идеальном варианте никто не использует насилие, потому что последствия будут хуже, чем любые профиты, которые от него можно получить.

В (анархо-)коммунизме решения крутятся вокруг идеи, что принуждение в обществе должно быть просто никому не нужно, чтобы это не было решением твоих проблем, даже если тебя никто не поймает. Если у тебя достаточно еды, тебе нет смысла ее воровать. Если сотрудник может покинуть работу в любой момент без экономических последствий, начальнику нет смысла его абьюзить. Если в обществе нет групп с резко противоположными интересами, между ними не будет войны. Цивилизация это когда мы вместе работаем над общей целью, а не грызем друг другу глотки, как животные.

Это может работать как на индивидуальном уровне – я ценный член общества, меня все любят, меня окружают друзья, так что меня никто не будет убивать, даже если может – так и на уровне коллективных систем – сильные экономические, социальные и культурные институты, которые в целом обеспечивают обстановку, в которой ты можешь получить без насилия все, что мог бы получить насилием. В идеальном варианте никто не использует насилие, потому что мы тут все союзники, такая мысль никому и в голову не придет.

Оба подхода не взаимоисключающи, в любом обществе будет применяться смесь. Анком все еще может пристрелить нападающего, а анкап все еще может не воровать, даже если знает, что не будет пойман. Но анкап использует первый подход как основной, на чем отсутствие принуждения фундаментально зиждится, а второй как побочный, которым затыкают дырки и уменьшают погрешности. Анком – наоборот.

Коммунисты строят фундаментально кооперативное общество, где принуждение не решит никаких проблем. Социализм в целом ставит задачей создать такую систему, которая работает на каждого, и против которой нет смысла идти, даже если можешь. В идеально-утопическом случае не нужны ни законы, ни полиция – потому что никто изначально не будет хотеть делать то, что эти законы бы запретили, в этом не будет никакой пользы. Более формально, социалистическая экономика строится как равновесие Нэша с положительной суммой, которое остается стабильным без необходимости его специально поддерживать. Ни у кого нет стимула его ломать.

Капиталисты строят фундаментально соревновательное общество – в основе рыночной экономики стоит в первую очередь конкуренция. И у тебя абсолютно есть стимулы нарушать равновесие, если оно нарушается в твою пользу. Если ты можешь выбрать “предать” в дилемме заключенного, пока другие выбирают “сотрудничать”, ты в плюсе. Воровство даст тебе больше денег. Газлайтинг подчиненных даст тебе больше продуктивности. Манипулятивный маркетинг даст больше продаж. Чем больше ты создашь проблем, тем больше продашь решений. Выбив конкурентов из бизнеса, ты увеличишь доходность своего бизнеса. В капиталистическом обществе на каждом шагу игры с нулевой и отрицательной суммой, когда твоя потеря это мое приобретение.

И возникающие вследствие этого проблемы решаются наказанием того, кто их создает. Ты не можешь воровать, потому что тебя за это оштрафуют (или пристрелят на месте). Ты не можешь убить конкурента, потому что за это посадят. Ты не можешь не выплатить работнику зарплату, потому что придет полиция и заставит.

-----

Если вы еще не заметили из абсолютной однобокости моего представления, я не особо люблю капиталистический подход. Он создает систему с фундаментальной проблемой, а потом пытается залатать ее набором надуманных правил, которым все должны следовать под страхом смерти, хотя никто этого не хочет. И эти правила порой могут быть очень запутанными и, особенно в случае поборников конкретно формулировки NAP, требовать постоянного талмудического толкования.

“Ты можешь использовать насилие, только если насилие применяют против тебя. Кроме случая, если ты взял что-то из моего дома. Тогда я все еще могу в тебя выстрелить, хотя ты меня даже не трогал, потому что насилие против моего пылесоса считается насилием против меня. Кроме случая, когда ты агентство по взысканию долгов, и вещи забираются для покрытия долга, потому что на самом деле у тебя нет полного права на собственность, если ты должен другим людям деньги. Кроме случая, когда ты влез в долги под влиянием угрозы, потому что тогда контракт не считается. Кроме случая, если угроза была умереть от голода, пусть ты бы и буквально умер в случае несогласия, потому что эта угроза появилась не из-за моих действий, она там изначально была, я не виноват. Кроме случая, когда у тебя нет еды из-за того, что [[https://www.urbandictionary.com/define.php?term=Coconut%20Island][я собрал все кокосы пока ты спал]], тогда да, угроза появилась из-за меня, но согласно мнению раввина Локка...” ну вы поняли. В средневековой Исландии, ближайшему, что в истории было к анархо-капитализму, самой востребованной профессией был юрист, и без достаточно сильного юриста под боком человек банально не мог выживать в обществе.

Капиталисты часто утверждают, что их система максимально простая, естественное состояние человечества в отсутствие правил, просто слово “СВОБОДА”, написанное капсом поперек страницы. Но для работы системы нужно /огромное/ количество правил, так или иначе насаждаемых насилием. Не обязательно государственным, но частная полиция все равно полиция.

(И потом у них хватает смелости говорить, что проблемы с неадекватными правилами будут решены за счет того, что будет много конкурирующих enforcing agencies, как будто /еще больше правил/ делает ситуацию лучше)

Другая проблема с патчингом фундаментальных проблем правилами в том, что достаточно умный человек всегда найдет способ их обойти. Сказать можно даже больше – обязательно кто-то найдет, потому что это выгодно, система это награждает и таких людей поддерживает. Награды идут самым умным rule lawyer.

Ты не можешь заставить людей платить за свои сигареты под дулом пистолета, потому что это нарушило бы NAP? Вообще не проблема, лол. Экономическая наука никогда не откажет придумать четыреста сравнительно честных способов заставить население покупать что-то, что им не нужно. Спонсировать исследования, показывающие, что сигареты лечат астму! Подкупать врачей, чтобы они советовали пациентам сигареты! Нанимать психологов на разработку хитрых манипулятивных тактик для рекламы, понижающих способность людей делать рациональные решения! Добавлять осколки стекла в фильтры, чтобы увеличить аддиктивность! Продвигать культуру, что курение это “круто”, чтобы неопытные подростки чувствовали социальное давление курить! Это разрушит здоровье целых поколений, израсходует бесчисленные человекочасы ученых, сожрет тонны ресурсов впустую, но технически ни против кого не было применено принуждение, значит система нас наградит! И ВВП вырастет!

(эти примеры не выдуманные – это все действительно делали табачные компании в США)

Капиталистический мир полон мошенников, хищников, бандитов, злодеев – потому что именно эти люди выигрывают в игре капитализма. Каждый – потенциальный враг. Надо всегда быть начеку. Неудивительно, что анкапы так фетишизируют огнестрел – в мире анкапа не выжить без возможности чинить насилие.

(а дети, живущие в таком обществе в определенные критические окна развития психики, настраиваются на low-trust society, и потом даже в нормальных, дружелюбных условиях не могут не вести себя как сволочи, создавая самоподдерживающийся цикл – но об этом потом)

Все постоянно плывут против течения, работают против системы, пытаются найти способ обойти правила. Когда все пытаются найти способ выйти из системы – это хороший индикатор, что система не очень. Жизнь внутри капиталистической системы никому не нужна, победители те, кто нашел способ ее избежать. Мечта обывателя – выиграть в лотерею. Бизнес-советы – как побеждать в играх с нулевой суммой. Маркетинговые советы – как путать людей и заставлять их вести себя иррационально. Начальники ищут способы платить работникам меньше, работники ищут способы работать меньше. Вы когда-нибудь работали разработчиком мобильной free-to-play игры? Там все про то, как абьюзить и газлайтить людей. Потому что это то, как ты становишься успешным при капитализме – делаешь других менее успешными.

Конечно, любые проблемы можно пытаться затыкать /еще/ правилами! Может, добавление осколков стекла в фильтры теперь считается насилием, даже если об этом написано мелким шрифтом на пачке? Может, советовать пациентам сигареты когда ты знаешь, что они вредны, нарушает правила какого-нибудь частного сертификационного агентства, которое отнимет у доктора лицензию, и он потеряет клиентов? А, стоп, агентство же тоже читает те ложные исследования и не знает, что сигареты астму не лечат... сейчас, дайте глянуть... слоты заклинаний от разных спеллкастерских классов складываются как... подождите, не ту книгу правил схватила...

Такие проблемы не предотвратить, затрудняя к ним доступ. Люди изобретательны. Если кто-то это хочет, это случится. В социалистическом обществе такой проблемы не встанет изначально, даже если никакие правила это не запрещают и никого ни за что не наказывают. Никому нет особого дела, куришь ты сигареты или нет. Хочешь – кури, не хочешь – не кури. Это твое решение, делай как считаешь нужным, система не будет награждать никого за то, чтобы они влияли на это решение.

В такой ситуации нет смысла придумывать сложные схемы правил и блюстителей закона. Если никому не нужно, чтобы что-то случилось, оно не случится, даже если нет закона, который бы это запрещал. Тебе не нужно поддерживать систему насилием, если никому не выгодно ее менять. Даже если в системе есть недостатки, проблемы, дыры – хотя бы она не поощряет их эксплуатировать

Конечно, это не будет работать всегда. Левацкая теория обычно фокусируется на политическом и экономическом принуждении, другие пока не так подробно разобраны (хотя мы работаем над этим!). Насколько я знаю, пока не придумана экономическая система, которая предотвращает детское изнасилование. Так что порой все же придется защищать себя насилием или изолировать некоторых от общества. Не сомневаюсь, что вам не составит труда найти много примеров, когда игры с нулевой и отрицательной суммой все же есть, и система пропускает удар. Но во всех этих случаях в капитализме они тоже есть, так что тут удар пропускают оба.

-----

Подводя итог...

Коммунисты строят общество, которое минимизирует насилие в своей базовой структуре, и прибегает к принуждению только в крайних случаях, когда иначе сохранить свободу нельзя, понимая при этом, что даже такое насилие – необходимое зло, и мы должны искать способы сделать лучше.

Капиталисты строят общество, полностью основанное на принуждении, и надеятся, что насилие, направленное во все стороны, сложится в нулевой вектор и каким-то образом оставит за собой свободу.

Следующий очевидный вопрос – а как сделать общество, в котором никому нет смысла шатать систему? Оставайтесь в треде до будущего поста! Спойлер: это достигается за счет того, что мы строим систему под людей с человеческой психологией и мотивациями, пользуясь научным знанием о человеческой природе, а не под абстрактную модель гомо-экономикус.
