#+TITLE: Коп в голове

В последнее время часто в онлайн-пространствах использую метафору “коп в голове”, и уже дважды меня спросили, что я имею под этим ввиду. Поясню, важная часть лора Принцессы и ее взгляда на религию.

Узнала я эту концепцию оттуда же, откуда узнала все, что я знаю и умею – из [[https://www.cs.cmu.edu/~tilt/principia/][Principia Discordia]]. Вряд ли эту идею придумал Малаклипс, она наверняка где-то была и раньше, но плевать.

Коп в голове – это навязанное культурой и обществом самоограничение. Само по себе это не плохо – совсем без тормозов и берегов жить в сосаети сложновато. Иметь принципы – хорошо. Но они должны быть /[[file:toolvslaw.org][инструментами]]/. Которые используются для какой-то цели.

Проблемы начинаются, когда принципы начинают использовать тебя. Когда ты не осознаешь, что они в голове у тебя есть. Когда ты выносишь их из контекста, в котором они полезны.

Самый очевидный пример – российская тюремная культура. В самой камере – допустим так, правила зашквародинамики и петушения имеют смысл для построения иерархии. Но люди несут эти идеи и вне тюрьмы. Человек не делает жене кунилингус, потому что это зашквар. Казалось бы, /вред то в чем/? Ни в чем, в этом правиле нет смысла. Но навязали. Коп не дает.

В деревне находим пустую церковь. Предлагаю зайти – просто посмотреть, что там, может полутать. Кузен наглухо отказывается. Почему? Он в бога не верит. Ага. Для него атеизм – это не просто фактическое понимание мира, а часть его гордости и самоопределения. В церкви заходить, не веря в бога – можно, не растаешь. Заход в церковь никоим образом не заставит нас подумать, что он верит в бога. Никакой практической причины не заходить – нет. Ему не дает коп в голове.

В Бразилии номер 24 считается “гейским” числом. Почему так – добро пожаловать в гугл, но люди реально в крендели изворачиваются, чтобы с ним не ассоциироваться. Например, на тортах на день рождения часто ставят свечку не с числом 24, а с 23+1. Казалось бы /совсем/ бесполезная традиция. Даже если ты считаешь, что быть геем это плохо, надо быть полнейшим кретином, чтобы предположить гомосексуальность человека за то, что ему исполнилось 24 года. Но я просто не хочу быть ассоциированным с гейством!

Когда adultempire.com переместил порно с транс-девушками из категории gay в категорию straight, просмотры возросли на 50%. Это то же самое порно про тех же самых людей для той же самой аудитории – но чисто из-за лейбла уровень удовольствия, которые получают зрители – меняется. Явно ими руководит не либидо и не сексуальные предпочтения – ими руководит коп.

В баре один отказался пить коктейль “негрони”, потому что название расистское. Мужик отказывается готовить, потому что это бабское дело. Ест банан вилкой и ножом, чтобы не выглядело, как будто сосет член. Мальчики в школе, терпящие весь день, потому что мужской туалет закрыт, а в женский идти зашквар.

Постоянные копы, пользы от которых нет.

-----

После прочтения “приципии” стало мгновенно понятно – у меня в голове не то что коп, а целое полицейское государство. И они наносят мне реальный вред.

Долгое время я пыталась выгнать их из головы и била себя плетками, что не достигаю стандартов правоверного дискордианца. Потом оказалось, что большая часть копов – результат маскулинности, и после избавления от конкретно этого Германа Геринга все они исчезли. Все ранее обнаруженные, я имею ввиду. Наверняка есть еще, о которых я и не знаю. Но мы работаем над этим. И, в любом случае, это пошло мне сильно на пользу – как минимум, количество вещей, от которых я могу получать удовольствие, возросло.

Теперь. Копы – плохо, и их всех надо изгонять? Нет, какие-то самоограничения полезны и хороши. Мир, состоящий исключительно из фулл дискордианцев нормально функционировать не будет.

Стандартная позиция дискордианской метафизики – что между порядком и беспорядком должен быть баланс, но наш мир сильно скошен в сторону порядка, и большинство наших проблем от этого. Что открывает два подхода к решению проблемы. Ты можешь поддерживать баланс на персональном уровне. Или ты можешь стать агентом беспорядка и смешать весы в обратную сторону, чтобы скомпенсировать порядок вокруг тебя. Раньше я была строго в первом лагере. Конституционно я была максимально лоуфул, и творить откровенный хаос и идти против общественного порядка мне смелости не хватало. После хеншина стало понятно, что это коп и самообман, а так-то я лично ближе ко второму. Клинический психолог так и сказал – ты себя подавляешь, так-то по тестикам ты basically Pinkie Pie. Всю жизнь качала лоуфульные скилы, а теперь переучиваться... эх.

Так или иначе.

“Надуманные правила” – вообще большая тема в дискордианстве, и “коп в голове” – только начало. Но об этом дальше.
