#+TITLE: Doomsday argument внушает надежду


Есть такой известный философский аргумент – Doomsday argument. Перескажу вкратце очень упрощенную версию.

#+begin_quote
Люди когда-нибудь вымрут, ничто не вечно. Пусть сразу после этого мы возьмем всех людей, которые когда-либо жили, и расположим их в линию согласно времени их рождения, от 1 до N. Дальше делим их на три группы – первые 5%, средние 90% и последние 5%.
Теперь каждого из них (не говоря ему его позицию в линии) спрашиваем – в какой ты, скорее всего группе? Самый правильный возможный ответ в отстутствии другой информации – “в средней”. Если все ответят “в средней”, то правы из них будут аж 90%.
Значит, мы сейчас с наибольшей вероятностью находимся в средней группе. До сих пор людей было около 100 миллиардов, значит с вероятностью 95% N меньше 2.2 триллионов. Если бы это было не так, это бы значило, что мы находимся в одной из 5%-групп – если бы все люди отвечали так, большинство из них было бы неправо.
Если население людей выйдет на плато в районе 9 миллиардов (как предсказывают текущие модели), то люди вымрут примерно через 800 лет. Если будет расти – то еще раньше.
#+end_quote

Почти все, кто читают этот аргумент, с ним не согласны. И все не согласны по разным причинам. И чем больше они его читают, тем больше меняют свои причины считать, почему он неверен. Было много работ, разбирающих аргумент, опровергающих его, опровергающих опровержения и так далее – консенсуса нет.

Но мне больше всего кажется интересным полный пессимизм, окружающий этот аргумент. Даже его название намекает, что вот мы все вымрем и это плохо. Нам осталось 800 лет, как это ужасно!

Но посмотрите с другой стороны – аргумент говорит, что мы одни из последних людей в очереди (для очень широкого понимания слова “последний”). Это совершенно не значит, что мы вымрем! Мы последние люди, которые будут рождены – это не значит, что мы умрем через 800 лет! Аргумент полностью совместим с тем, что последние люди в очереди будут жить по миллиону лет каждый, например.

И обратите внимание – срок “судного дня” зависит от количества людей в будущем. 800 лет – это если текущие прогнозы населения Земля будут выполняться. Но чем больше население будет расти, тем ближе “судный день”. Если бы текущие прогнозы говорили, что население вырастет до 20 миллиардов – срок был бы ближе, и аргумент был бы вероятностно сильнее. Чем больше людей будет в будущем, тем ближе момент “судного дня”, после которого больше людей появляться не будет.

Да, аргумент говорит слегка в пользу того, что ничего не будет особо меняться следующие 800 лет, а потом мы все умрем.

Но он немного вероятностно больше совместим с предсказанием, что совсем скоро – не через 800 лет, а куда раньше – население людей вырастет очень резко, вероятно куда больше, чем может держать Земля, а потом все перестанут умирать.

Может быть, его стоило назвать Singularity argument?

Я порой оптимист.
