#+TITLE: Необъяснимость чудес опровергает существование Бога
#+LANGUAGE: ru
#+DATE: <2026-08-31 Mon>

На substack нынче популярен [[https://benthams.substack.com/p/a-clash-of-titans-the-ethan-muse][дискурс вокруг божественных чудес]], в частности [[https://en.wikipedia.org/wiki/Miracle_of_the_Sun][Чуда Фатимы]], и доказывает ли оно истинность католицизма/существование Бога. Некоторые участники опровергают его на основе мета-соображений – например, показывая на аналогичного масштаба чудеса, говорящие в пользу /других/ религий. Но самая популярная линия атаки – пытаться найти натуралистическое объяснение чуду: объяснить с точки зрения науки, что же там произошло. Фоновое предположение за этим – что если натуралистического объяснения нет, значит Бог есть. Даже Скотт Александр после [[https://www.astralcodexten.com/p/the-fatima-sun-miracle-much-more][своей первой неудачной попытки все объяснить]] слегка забоялся, что ад реален (хотя потом сделал [[https://www.astralcodexten.com/p/waiting-for-the-miracle][вторую, более успешную попытку]]).

Что для меня чувствуется очень странно, потому что при моих priors наличие натуралистического объяснения /увеличило/ бы вероятность существования Бога.

На фоне обсуждений за чудеса есть наивная картина мира, в которой существование Бога подразумевает постоянные чудеса и магию, а отсутствие Бога – мир-механизм, в котором все происходит предсказуемо по формулам. Но это не настоящая /модель/, которая предсказывает наблюдения и на которую можно применять теорему Байеса, это расфасовка наблюдений в два якобы противопоставленных литературных жанра: „наука“ и „религия“. Если пытаться все же мыслить вероятностно из такой картины, модель получается вырожденная. Бог может сделать что угодно, и его мотивация неисповедима – поэтому никакое наблюдение не считается против религии. С другой стороны, наука как бы должна объяснять всё на свете, поэтому любые лакуны в нашем понимании считаются против науки.

Ни то, ни другое, на самом деле не предсказывается ни теизмом, ни натурализмом. Со стороны натурализма – мир просто странный. [[https://johnsalvatier.org/blog/2017/reality-has-a-surprising-amount-of-detail][Реальность содержит удивительное количество деталей]]. В нем много необъясненных вещей, странностей, аномалий, удивительных совпадений, намеренных мистификаций и кажущихся парадоксов. Какие-то из них рано или поздно находят объяснение (напр. инцидент на перевале Дятлова), какие-то до сих пор непонятны (рукопись Войнича). И речь даже не о несовершенстве научных знаний – многие тайны невозможно решить, просто потому что прошло слишком много времени, и энтропия вселенной стерла все зацепки. И даже те зацепки, что у нас есть, порой доходят до нас через десять слоев сломанного телефона. И это еще даже до того, как мы говорим о на самом деле неизведанных и не описанных наукой явлениях, которые тем не менее предположительно вписываются в натуралистическую картину мира (мы точно не знаем, как работает шизофрения, но предполагаем, что теоретически там есть какой-то не противоречащий законам физики механизм).

С другой стороны, теизм не то чтобы /предсказывает/ чудеса типа Фатимы. Есть целый пласт теологии вокруг [[https://en.wikipedia.org/wiki/Divine_hiddenness][божественной сокрытости]], и я видела немало обсуждений Бога в рамках аналитической философии, которые объясняют, почему Бог бы создал предсказуемую вселенную, следующую физическому закону. Некоторые решения проблемы зла тоже подразумевают, что Бог не будет просто так вмешиваться в ход вселенной по мелочам. С другой стороны, например, Бог в ветхом завете вмешивается очень очевидно, так, что ни с чем не спутать, и увидев, отрицать его существование было бы глупо. Что та, что другая картина Бога мне кажется вполне приемлемой. Но если чудеса типа Фатимы происходят по божественному вмешательству, нарушая законы физики – то получается, что Бог в целом поддерживает физическую вселенную, но иногда, очень редко, для отдельных случайных людей, которые оказались в нужном месте в нужное время, организовывает чудо, которое находится на самой грани доверительности. И при этом он даже не делает что-то полезное (Иисус хотя бы лечил больных и кормил голодных), а просто совершает что-то аномальное, но ничем кроме своей аномальности не значимое. Это совершенно не что-то, что я бы ожидала видеть, если Бог существует. В сокрытого Бога, или в Бога, который очевидно вмешивается только в очень значимых случаях типа пришествия Христа – я еще могла бы поверить при достаточно хороших аргументах или если лично ангел спустится и пояснит, здесь моя субъективная вероятность, допустим, 1%. Но такого бога-пятиклассника я исключаю +- полностью, 0.0000001%.

Мы точно не живем в мире, где Бог очевиден как в ветхом завете, чудеса не происходят постоянно и регулярно, я ни разу не видела ангела. Либо мы живем в полностью натуралистическом мире; либо мы живем в мире с Богом, который не стал бы делать такие тупорылые чудеса. Ни в одном из случаев /конкретно чудо Фатимы/ не произошло по непосредственному божественному вмешательству. Оно точно произошло полностью в соответствии с законами физики, даже если эти законы создал Бог.

Так что когда я слышу, что аномалию не может объяснить ни один ученый – я не думаю „вау, это значит, что Бог существует“. Я думаю „вау, мир действительно очень сложный, и наша способность его объяснить сильно ограничена“. Чем больше таких аномалий я вижу, тем больше я убеждаюсь, что мы плохо умеем объяснять и мало понимаем, как работает мир. Моя вероятность существования Бога не меняется – вместо этого вероятность перетекает из „мы способны объяснить мир, каждая аномалия это проблема“ в „мы не способны объяснить мир, аномалии можно принимать как они есть“.

Но есть также и много других вещей, которые теизм /на самом деле/ предсказывает лучше, чем известные нам законы. [[https://philopedia.org/arguments/fine-tuning-argument/][Тонкая настройка вселенной]], например. [[https://en.wikipedia.org/wiki/Hard_problem_of_consciousness][Трудная проблема сознания]]. „Почему вселенная вообще существует изначально“. Для этих проблем есть предварительные и нечеткие натуралистические объяснения, но полного консенсуса нет. Я не считаю эти проблемы фундаментально непреодолимыми, вероятно для них таки есть решения, не требующие Бога, возможно читатели предложат несколько. Но [[https://en.wikipedia.org/wiki/Bayes_factor][в сравнительном смысле]], существование Бога бы объяснило их напрямую. Конечно Бог бы тонко настроил вселенную так, чтобы в ней могла существовать жизнь, это намного больше похоже на Бога, чем мультики с Фатимой в небе. Чисто формально нерешенность этих проблем – свидетельство существования Бога. Недостаточное, чтобы только на основе этого верить, и уменьшающееся по мере того, как мы эти проблемы решаем, но все же ненулевое.

Итак, суммируя. Я слышу „чудо Фатимы никто не может объяснить“. Я также знаю, что у чуда Фатимы теоретически есть объяснение, не требующее Бога. Раз мы не можем его найти, значит мы реально просто тупые и плохо находим объяснения. Аномалии, которые мы не можем объяснить, ничего не ломают – любые непонятки полностью объяснимы нашей глупостью. Это относится и к непоняткам, которые служат свидетельством существования Бога! Так что они тоже ничего особенно не значат. Мы не знаем, почему вселенная тонко настроена – ну и ладно, мы не знаем много вещей, мы обезъяны с претензиями. Моя вера в Бога /падает/, потому что часть свидетельства в пользу Бога теряет силу.

А если я после этого услышу, что натуралистическое объяснение таки найдено, то все эти соображения отменяются. Моя вера, соответственно, вернется на прежнее значение – увеличится.

---

Я пишу об этом, потому что заметила эту странность в своем же мышлении. Почему-то когда я услышала про чудо Фатимы, я почувствовала, что атеизм торжествует, а когда потом увидела устраивающее меня объяснение – что атеизм, наоборот, получил удар. Эта интуиция казалась мне справедливой, хотя рационально это было странно и не соответствовало тому, как остальные говорят об этом чуде. Так что я пошла распутывать конкретно, почему моя интуиция работает именно так, рефлексировать о том, какое вычисление произошло у меня под капотом, и справедливо ли она на самом деле, или просто баг/когнитивное искажение. Пришла к выводу, что абсолютно справедливо и не баг, все соответствует формальной теории вероятностей. Так что описала здесь.
