#+TITLE: Аддикция в Fallout: Equestria

Одна из причин, почему я так люблю Fallout: Equestria, это то, как замечательно у нее получается синхронизировать твои чувства с чувствами протагониста. Я не знаю, как автор это делает, но ты чувствуешь /все/. Когда протагониста бьют, ты вздрагиваешь. Когда протагонист пугается, ты подпрыгиваешь в кресле. Эта магия работает, судя по всему, не на всех – но на многих, включая меня.

Ничего не показывает этот аспект книги лучше, чем борьба Литтлпип с наркотической зависимостью. Ближе к началу ее приключения она находит коробку “Праздничных минталок” ([[https://fallout.fandom.com/ru/wiki/%D0%9C%D0%B5%D0%BD%D1%82%D0%B0%D1%82%D1%8B][ментатов]]). Как и в оригинальных играх, они временно повышают ее интеллект и внимательность, но чрезмерное принятие ведет к зависимости, которая, наоборот, понижает твои параметры, пока ты не под действием наркотика.

Поначалу она принимает минталки периодически, в сложных случаях, когда не может без них справиться. Это очень сильно помогает, так что она принимает их больше и чаще. Потом просто ради удовольствия или из привычки, даже если и без них можно справиться. Рано или поздно она начинает замечать, что она “сама не своя”, пока не под минталками, что только с ними она чувствует себя нормально.

Наконец, ее друзья вмешиваются и тащат ее к доктору, который очищает ее организм от наркотика (да, во вселенной Fallout оно так работает). Он предупреждает ее, что пусть химическая часть зависимости и вылечена, психологическая никуда не делась, и если она снова начнет принимать наркотик, ее зависимость вернется.

После процедуры Литтлпип чувствует себя обновленной, отдохнувшей, счастливой, с ясной головой. Сначала она думает, что она под кайфом от анестезии, но потом понимает, что то, как она чувствует себя сейчас – это была ее “норма” до того, как она начала принимать минталки. Все это время она была заторможенной, ослабленной, нервной, с туманом в голове. И только под действием наркотика она могла быть хоть немного функциональна.

/И я все это чувствовала!/

Я чувствовала подъем настроения, когда она принимала наркотик. Я чувствовала заторможенность и подавленность, когда эффекты прекращались. Часто я замечала, что не могу уже дождаться, пока она не примет очередную таблетку, или злюсь, если ей что-то мешает это сделать. Я чувствовала туман в голове – в последних главах перед прочисткой я была заторможена и спутана, словно мой мозг не совсем работает. Все события в книге меня раздражали или вызывали дискомфорт – пока она не принимала свои таблетки. И когда она прошла через процедуру – я действительно почувствовала, будто мозги прочистились и гора спала с плеч. Только тогда я поняла, насколько отвратительно я себя чувствовала последние несколько глав, по мере того, как зависимость Литтлпип углублялась. /Я все это прочувствовала/.

Я не знаю, насколько это отражает зависимость в реальной жизни – я ни разу не подсаживалась на наркотик. Но если в реальной жизни оно так и работает – мои соболезнования аддиктам, теперь я понимаю, как наркотическая зависимость может разрушать жизни и семьи.

Спустя какое-то время Литтлпип находит свой большой запас минталок и задумывается – оставить их на случай, если в критической ситуации потребуется бонус, или выкинуть, чтобы не рисковать возвратом болезни? И это действительно была дилемма, настоящая, на которую у меня не было четкого ответа.
