#+TITLE: Почему лудомания не работает на добро?

Есть такие злые чуваки от гейм-дизайна – разработчики казино. Мне приходилось кратко поработать штатным математиком для онлайн-слотов – эта область /очень/ хищническая. Мы все понимаем, что разработчики игр при капитализме думают о выжимании денег, а не о том, чтобы сделать игру веселее, но конкретно в этой области идея доведена до апогея. Вопроса доставить игроку удовольствия вообще не стоит – вместо этого приводится часто игнорируемая нейрологическая идея, что механизмы /хотения/ и механизмы /удовольствия/ вообще-то вещи разные, и вполне можно – и нужно – сделать так, чтобы происходящее доставляло игроку только страдания, но он при этом возвращался в игру снова и снова.

И это мелкие слоты от мелкого разработчика. В каком-нибудь Вегасе сидят куда более умные гейм-дизайнеры, чем я, и образ лудомана, который сливает за вечер свою годовую зарплату, уже стал культурной иконой. Часто доходит до безумия – была там одна девушка, которая слила все свои деньги в автоматы, потом вернулась в номер и нашла на прикроватной тумбочке непотраченную купюру. От того, что она не смогла ее слить, она встряла в такой психоз, что пришлось увозить на скорой (источник: /Addiction by Design: Machine Gambling in Las Vegas/ – в целом не рекомендую, довольно душная книга).

Я сейчас не о том, что таких гейм-дизайнеров надо вешать. А о том, что если на 20м уровне класса гейм-дизайнера открывается такой майнд-контроль, почему никто не использует его во славу добра?

Гамификация. Идея, что пользуясь теми же механизмами и приемами, можно провоцировать людей на хорошие вещи. Обучение, продуктивность, маркетинг. Приложух, которые используют эту идею, полно. Duolingo, Habitica, Zombies, Run!, SuperBetter...

Но они не работают так хорошо. Ни разу не слышала про ситуацию, когда человек аддиктится и несколько суток непрерывно изучает финский на Duolingo до такой степени, что теряет работу и семью и отъезжает с психозом.

Почему так? Просто менее скиловые гейм-дизайнеры, чем в Вегасе? Вряд ли – мелкие казино тоже зарабатывают неплохо. Физические деньги имеют другой психологический вес, чем виртуальные? Более возможно, но не думаю – есть полно игроков в free-to-play мобилочки, которые сливают всю свою валюту в рероллы лутбоксов, как только получают, при этом не внося ни копейки реала, да и реал эти приложухи тоже частично жрут.

У меня нет ответа. Я реально спрашиваю. Почему?
