#+TITLE: Логика высоких энергий

_В предыдущих сериях_: [[file:highenergyphilosophy.org][Философия высоких энергий]]

Есть у многих ужасная привычка – пытаться выводить философские или политические мнения логически из первых принципов. Это [[file:factsandlogic.org][никогда не работает]], но почему-то в любом споре логическая цепочка от аксиом к выводам считается гипер-убийственным аргументом, и если твой оппонент не может ответить на “покажи, в каком именно месте я ошибся в рассуждении” – то можно присуждать себе победу. Ведь если дать правильные определения словам – списки достаточных и необходимых свойств, которые строго разбивают мир на Х и не-Х, и которые можно применять как предикаты к предметам в реальном мире – и доказать что-то /математически/, то оно доказано /в принципе/, верно? В этом же суть математики?

В настоящей математике такой подход работает только и исключительно из-за /крайне душных/ требований к математической строгости. 99.99% строгость недостаточна. Если есть хотя бы одно слово во всем аргументе, которое вы не можете полностью выразить символами языка (например) теории множеств Цермело-Френкеля – то это не логический аргумент. Он в лучшем случае /логичный/. Что тоже очень хорошо! Аргументы должны быть логичными! Но это совсем другая вещь, с которой нужно иначе работать. Если речь идет о логичных, но не строго логических аргументах, то совершенно допустимо быть согласным со всеми предпосылками, согласным со всеми промежуточными шагами, но не согласным с выводами. Совершенно возможно иметь два одинаково логичных аргумента, выводы которых противоречат друг другу. Совершенно возможно опровергнуть логичный аргумент еще более логичным.

Если пытаться брать логичные аргументы (или, как оно часто бывает, логикообразные) аргументы и рассматривать их как логические – можно убедить себя в любой ерунде, или даже в нескольких противоречащих друг друг ерундах одновременно. Хуже того, можно стать полностью имунным ко всем попыткам себя переубедить; самоуверенность фатально ошибающихся техбро, залогировавших себя в угол, осмеивалась даже в /xkcd/.

Что как метод познания это не работает, должно быть очевидно хотя бы потому что исторически так приходили к совершенно противоположным выводам. Если ты, читатель, не христианин, то для тебя может быть сходу убедительным тот факт, что такие весьма внушительные люди как Рене Декарт, Готфрид Лейбниц или Святой Ансельм вывели логически из первых принципов существование христианского Бога, и ошибки в их рассуждениях никто не мог найти веками. А если ты, читатель, не монархист, то Томас Хоббс так же вывел необходимость абсолютной монархии. Если ты христианский монархист, то тебе к настоящему психиатру, а не к недоучке с блогом, но всем остальным должно быть понятно, что это не настолько непробиваемая тактика, как может показаться. Логика  не работает /сама по себе/, она только дает структуру мыслям, следуя закону “мусор на входе – мусор на выходе” [fn:: где “мусором на входе” могут быть не только ложные предпосылки]. Она защищает тебя от некоторых ошибок в рассуждениях, но даже близко не от всех.

Это относится не только к спорам в интернете, но и к личной эпистемологии. Надо всегда относиться с подозрением к любой идее в своей голове, которая составлена на основе длинной цепочки соображений. Если вам нужно сорок логических шагов, чтобы дойти от самоочевидных аксиом до итогового мнения, и каждый шаг на 98% справедлив, то вы не будете видеть ошибку ни в одном из них, все они будут чувствоваться верными, и на вопрос “где именно здесь ошибка в рассуждении” ответа не будет. Но вся цепочка будет скорее неверна, чем верна.

Я, в целом, советую дикий синкретизм и [[https://en.wikipedia.org/wiki/The_Hedgehog_and_the_Fox][лисью эпистемологию]], при которых убеждения собираются по кусочкам на основе как можно разнообразного и большого числа соображений, источников и точек зрения, включая, но не ограничиваясь логическими умозаключениями. Но если все же /очень хочется/ вывести что-то чисто логически… или если вы читаете чей-то чужой аргумент, который ограничивается логической цепочкой и считает, будто на этом все и должно закончиться…

Иногда нужны способы разбивать такого оппонента. Оппонентом может быть спорщик, или им можете быть вы сами в процессе рефлексии – в любом случае поможет попробовать взять логический аргумент и /на самом деле/ применить на него всю силу математической строгости. И если это покажется вам душной придиркой – что ж, значит аргумент как минимум частично ошибочный, и мы просто торгуемся о величине ошибки. И это хороший способ искать конкретные слабые места – места, где интуиция оппонента дала ложную подсказку, или где он на самом деле не полностью разбирается в ситуации.

Давайте я покажу вам несколько веселых логических формул, которыми можно обстреливать логический аргумент для проверки на прочность. Для затравки.

** $((A\implies B) \vdash (A\land C \implies B))$

Перевод на русский: если из неких предположений следуют некие выводы, то это не перестанет быть правдой от добавления новых предположений.

Иными словами, если кто-то утверждает, что из А следует B, то вы можете додумать любые дополнительные [fn:: не противоречащие А; технически формула останется верной даже с противоречием, но только как vacuous truth] факты, какие вам вздумается, даже если в изначальные предположения они не входят. Если B от этого перестает быть правдой – что ж, значит в рассуждениях где-то ошибка.

Частным случаем этой формулы является “доведение до абсурда” – что на самом деле полностью кромулентный логический прием, запятнанный ассоциацией с софистическим приемом пропаганды. Но можно и не только доводить до абсурда имеющиеся предположения – можно добавлять совершенно новые, любые.

Айн Рэнд очень логично обосновала, почему, если человек смог заработать много денег, то он умный и достойный, а значит сделает со своими деньгами много добра. Окей, а что если после первого миллиона долларов у людей внезапно происходит повреждение мозга, превращающее их в дебилов? Здесь не обязательно утверждать, что это реально может быть – просто это сразу открывает целый пласт возможных возражений по поводу того, насколько люди меняются со временем. Дальше мы уже торгуемся, насколько именно и в каком качестве.


** $(A\vdash B)\land (A\land B \vdash \bot) \vdash (A \vdash \bot)$ [fn:: эта формула выглядит страшнее, чем она является по сути, потому что из соображений математической душности нужно соблюдать разницу между “следует из“ и “выводится из“ – она есть!]

Искать ошибку в рассуждении может быть сложно. Для этого надо проверить все предпосылки и все шаги. Пока вы будете это делать, оппонент уже придумает следующий плохой аргумент. К счастью, если вы сумеете показать, что из этого же рассуждения следует ложь, это с логической точки зрения совершенно то же самое, и обычно намного проще.

Аргумент против аборта из книги /After Virtue/ [fn:: я это взяла из [[https://slatestarcodex.com/2013/04/13/proving-too-much/][чужого поста]]; я не читала книгу]

#+BEGIN_QUOTE
I cannot will that my mother should have had an abortion when she was pregnant with me, except perhaps if it had been certain that the embryo was dead or gravely damaged. But if I cannot will this in my own case, how can I consistently deny to others the right to life that I claim for myself? I would break the so-called Golden Rule unless I denied that a mother in general has a right to an abortion.
#+END_QUOTE

Опровержение: допустим моя мать изнасиловала моего отца, и это привело к моему зачатию. Получается, было аморально ее остановить? И в целом останавливать изнасилования нельзя, если там есть шанс зачатия ребенка? Бум! Опровергнуто - и для этого совершенно не обязательно распутывать понятия Золотого Правила или обобщений прав или чего угодно другого сложного, что сказал автор.

Если оппонент признает, что останавливать изнасилования можно, то мы уже согласились, что лишать других права на жизнь можно, и теперь мы только торгуемся, когда это хорошо, а когда плохо.

** $\overline{(A\land B)} \vdash (\overline{A}\lor \overline{B})$

Также известен как закон де Моргана. По-русски – чтобы отрицать утверждение целиком, достаточно отрицать хотя бы один его компонент; не обязательно отрицать _все_.

На сервере Солнечной Империи нарушения этого закона замемились как “законы антишариата”. Сценарий платинового треда:

- я отрицаю институт частной собственности
- мне рассказывают, насколько будет плохо не иметь права на собственную зубную щетку
- я возражаю, что с чего бы то что-то вообще было с твоей зубной щеткой?
- меня вопрошают, а что помешает ее отобрать, если права собственности ее не защищают

Законы шариата запрещают убийство, а я против законов шариата. Значит ли это, что я за убийство? Нет – шариат запрещает много что; чтобы быть против шариата, мне достаточно быть против хотя бы одного запрета, не против всех сразу. Отрицать законы шариата не значит поддерживать законы полной противоположности шариата (“антишариата”). Институт частной собственности делает много что, кроме защиты зубных щеток – так что я могу одновременно утверждать право на зубные щетки и отрицать право на частную собственность.

В риторике и рассуждении этот закон нужен, чтобы разбивать черно-белое, бинарное мышление оппонента. Отрицание белого не значит черное. Отсутствие идеального решения не значит отсутствие частичного. Быть против частности не значит отрицать общность. И как только эта ошибка была найдена – дальше мы уже торгуемся, насколько много там серых зон и промежуточных вариантов.
