#+TITLE: Момент счастья

Не первый раз я слышу [[https://youtu.be/kq6Pe2dm0Uk?t=156][нарратив]], что когда люди прыгают с моста, чтобы убить себя, они сожалеют об этом в полете, но уже становится поздно. И если выживают и просыпаются, они неизбежно очень рады, что выжили.

#+begin_quote
“I realized then that all of the problems in my life that I thought were unsolvable were in fact solvable–-except for having just jumped.”
―  [[https://www.goodreads.com/quotes/8465177-i-realized-then-that-all-of-the-problems-in-my][Ken Baldwin]]
#+end_quote

Это, конечно, [[https://pmc.ncbi.nlm.nih.gov/articles/PMC1129714/?page=3][не универсальный опыт]], насколько бы многие ни старались преподнести его как таковой. Я ни разу не прыгала с моста, но я лежала на рельсах перед приближающимся поездом, что с учетом относительности скорости примерно то же самое. Когда поезд был в нескольких метрах от моего лица, когда я была уверена, что я прошла точку невозврата и уже не сумею передумать или увернуться, мои ощущения были скорее такими:


#+HTML: <iframe width="560" height="315" src="https://www.youtube.com/embed/V9a38oslKxg?si=oytqYoVdEaT7Lfyg&amp;clip=UgkxTxC1NQgp5uRxQX5tAJ66RC1t9BMxBYuu&amp;clipt=EPjMAxiImwQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen=""></iframe>

Я была счастлива, впервые в жизни. Чувство облегчения было не сравнимо ни с чем. /Я это сделала/. У меня /наконец-то/ получилось. /Это закончилось/. Я свободна.

И когда я проснулась в реанимации, я была очень разочарована и очень в ярости. Я однозначно не была рада, что выжила.

Этот момент бесконечного спокойствия и умиротворения – мой “дракон”, за которым я до сих пор гонюсь.

Единственный момент, когда я была счастлива.
