#+TITLE: Времена в английском языке без буллшита
#+LANGUAGE: ru
#+DATE: <2026-07-26 Sun>

/Технически некорректный, но педагогически полезный урок английского. Лингвисты DNI/

В английском языке три времени: настоящее, прошедшее и будущее. Остальные – псиоп и пропаганда, чтобы продать больше уроков. Я уже не преподаю английский, и потому обличаю индустрию.

Чем в русском языке отличаются времена? Формой глагола. “Я выиграл, я выигрываю, я выиграю”. Так же и в английском.

* Настоящее время

Если местоимение =I, we, you= → глагол без окончания. I _win_, you _lose_.
Если местоимение =he, she, it= → глагол с окончанием =-s/-es=. She _wins_, he _loses_.

Исключение: глагол “быть” (be). Он спрягается по своему. Это не страшно, в русском языке он тоже исключение. “Я был”, “я буду”, а в настоящем? “Я являюсь”. Вот так же и в английском.

Местоимение =I= → =am=.
Местоимение =we, you= → =are=.
Местоимение =he, she, it= → =is=.

I _am_, you _are_, she _is_.

* Прошедшее время

Хорошие новости: от местоимения не зависит. В любом случае окончание =-ed=. I _destroyed_, you _destroyed_, she _destroyed_.

Плохие новости: неправильные глаголы. Они спрягаются по своему. I _win_ → I _won_. В русском такие тоже есть, но их мало и всем пофиг. А в английском их много, и их нужно просто запомнить, других вариантов нет.

Самые важные, которые нужно знать сейчас: =be= → =was/were=, =have= → =had=, =do= → =did=.

* Будущее время

Его в каком-то смысле тоже почти нет. Своя форма будущего времени есть только у глагола =be= → =will=, да и то она сама по себе не работает. На практике можно считать, что форма будущего времени глагола звучит как =will + глагол=. I _will win_. You _will eat_. She _will destroy_.

И, да, даже если основной глагол в предложении “быть” – он все равно ставится как “will + глагол”. Да, это значит что будет два глагола “быть” подряд. “Я буду дома” – “I _will be_ at home”.

Важно! Глагол после will не спрягается никак. She _will destroy_, /не/ she will destroys.

* Остальное

** Совершенность глаголов

В русском языке есть замечательная фича – совершенность глаголов. В зависимости от того, говорим ли мы о действии или о результате, мы спрягаем глагол по разному. “Я выигрывал” – действие. “Я выиграл” – результат.

В английском такая фича тоже есть, но устроена она костыльнее. Надо говорить буквально через глагол have, что ты /имеешь/ результат. “Я уничтожил противника” – “I _have_ destroyed the enemy”. Типа, сейчас у тебя есть результат – уничтоженный противник. Ты уничтожал противника, и вот он сейчас лежит уничтоженный, ты его имеешь. Отсюда логика: have + прошедшее время.

/Кроме неправильных глаголов/, конечно же. У них в этой ситуации прошедшее время образуется, опять же, по своему. Всесто I have did – =I have done=. Вместо I have was – =I have been=. Это тоже надо запомнить, иначе никак.

Эту конструкцию дальше можно ставить в любое из трех времен – настоящее, прошедшее или будущее. Ты говоришь про результат – уничтоженный противник. Когда у тебя этот результат есть? Вот так ты и склоняешь глагол в этом предложении по таким же правилам. Только глагол в данном случае всегда have – ты /имеешь/ результат.

Противник лежит уничтоженный сейчас – настоящее время. “I _have_ destroyed the enemy”.
Противник лежал уничтоженный раньше – прошедшее время. “I _had_ destroyed the enemy”.
Противник будет лежать уничтоженный потом – будушее время. “I _will have_ destroyed the enemy”.

Обрати внимание на разницу во времени между русским и английским языком. “Я уничтожил противника” – “I have destroyed the enemy”. В русском языке нет настоящей формы совершенного глагола. Мы можем сказать “я уничтожил” или “я уничтожу” – но эквивалента в настоящем времени нет. “Я уничтожаю” это уже про процесс, а не про результат. Если ты говоришь о результате, который имеешь /сейчас/, ты все равно говоришь о нем в прошедшем времени. Противник лежит уничтоженный сейчас, ты все равно говоришь “уничтожил”. В английском языке такой проблемы нет, если у тебя есть сейчас уничтоженный противник, ты говоришь об этом в настоящем времени, глаголом =have=.

* Отглагольные существительные/прилагательные

Глагол можно переделать в существительное, которое обозначает процесс. Бежать – бег. Читать – чтение. Также глагол можно переделать в прилагательное, которое обозначает состояние. Бежать – бегущий. Читать – читающий.

В английском языке обе эти вещи образуются одинаково – как глагол + -ing. Running, reading. На этом можно было бы закончить, ничего более сложного в этих формах нет, даже своего эквивалента неправильных глаголов нет. Но англичане используют эти слова чаще, чем русские, поэтому лучше на этом остановиться.

Дело в том, что когда речь идет о каком-то продолжительном процессе, в английском языке предпочитают говорить об этом через отглагольные прилагательные/существительные. Вместо “я бегу” говорят “я являюсь бегущим”, вместо “я читаю” – “я являюсь читающим”. I _am_ running, I _am_ reading. Разница в смысле между “I _run_​” и “I _am_ running” (ака “Я бегу” и “Я бегущий”) в том, что в первом случае нас интересует действие, во втором – процесс. Эти две вещи взаимозаменяемы чаще, чем может показаться, если слушать учителей английского в постсоветских школах.

И, конечно же, это тоже можно ставить в любое из трех времен. Помня, что be – исключение и неправильный глагол, и спрягается как =am/is/are/was/were/been= в зависимости от времени и местоимения.

“Я бегал вчера” → “I _was_ running yesterday”.
“Я бегаю сейчас” → “I _am_ running now”.
“Я буду бегать завтра” → “I _will be_ running tomorrow”.

** Оба сразу

Два предыдущих трюка – отглагольное прилагательное для процесса и совершенная форма для результата – могут использоваться одновременно. Если нас интересует /результат процесса/, мы можем использовать форму =have + глагол= для обозначения результата, и =be + глагол-ing= для обозачения процесса. Правила здесь все те же и работают так же, просто на место “глагола” в первой форме ставится глагол =be= из второй формы. Работает как конструктор.

Вот предложение: I _have_ been destroying my enemies.
- Это процесс, так что пишем been destroying, глагол be + глагол с окончанием -ing.
- Глагол be ставится в совершенную форму: have + прошедшее время.
- Be это неправильный глагол, поэтому пишется по особенному – been.
- Отсюда полная форма: _have_ been destroying.
- Я уничтожал своих врагов весь день, и поэтому сейчас устал. Результат длительного процесса.

И эту двойную форму тоже можно ставить в одно из трех времен: настоящее, прошедшее, будущее, меняя спряжение глагола have. Конструктор можно собирать сколько угодно сложно, навешивая больше деталей.

I _had_ been destroying my enemies. На защите диплома пять лет назад я весь день уничтожал своих врагов и к вечеру устал. Это был /процесс/ (уничтожение), меня интересует /результат/ (устал), и это все происходило в /прошлом/. Раз я имею результат, то этот глагол – have. Так как в прошлом, то глагол ставится в прошедшее время (had). И так как процесс, то be destroying.

Если это будет происходить в будущем, то, соответственно, I _will have_ been destroying my enemies. Не знаю, будет ли такая конструкция встречаться в реальном мире, но она легальна.

* Но я думал времен 12!

...потому что почему-то совершенные формы и отглагольные прилагательные тоже считают частью времени. В русском это не так, в русском считаем, что это отдельные свойства глагола, к времени не имеющие отношения. 12 времен получаются, так как у тебя 3 /нормальных/ времени (прошлое, настоящее, будущее), каждое из них может быть в одной из двух форм (совершенная, несовершенная), и каждое может быть с обычным глаголом или с отглагольным прилагательным. 3*2*2 = 12. Очень незаслуженно страшное число, и я надеюсь сейчас смысл этой таблицы понятен лучше.

|           | Действие       | Процесс           | Результат       | Результат процесса        |
|-----------+----------------+-------------------+-----------------+---------------------------|
| Прошлое   | Past simple    | Past continous    | Past perfect    | Past perfect continous    |
| Настоящее | Present simple | Present continous | Present perfect | Present perfect continous |
| Будущее   | Future simple  | Future continous  | Future perfect  | Future perfect continous  |
