#+TITLE: Транс-аллегория Cyberpunk 2077

Читаю постики про Cyberpunk 2077 (не понравилось, не рекомендую) [fn:: Пост был написан до обновлений, которые значительно исправили игру – так что нерекомендация неактуальна]. Много вижу жалоб на транс-репрезентацию. Что, мол, возможность прикрепить член на девушку это прям совсем голимая попытка успокоить транслюдей, что выбор не влияет практически ни на что, что нет опции they\them, что идентичность гвоздями прибита к голосу... Интернет, кажется, считает, что CD Project Red вообще не попытались поисследовать вопрос транс-опыта и свели все к “ха ха, неправильные гениталии”. Энергия “мы исследовали предпочтения лесбиянок, проведя опрос n=1000 белых гетеросексуальных мужчин”.

Неужели все пропустили гигантскую транс-аллегорию посередине? Во всяком случае, нагуглить этот тейк мне не получается (skill issue?), так что дам его здесь.

Ближе к началу игры вам в голову вселяется Джонни. Теперь у вас в голове живет агрессивный, токсичный мужик, который вас ненавидит и пытается вас убить. Он вмешивается в ваш мыслительный процесс, не давая нормально мыслить и функционировать. Когда вы смотрите в зеркало, вы видите этого мужика вместо себя, отчего вам глубоко неприятно, и зеркало хочется разбить. Вам дают таблетки, которые временно его подавляют, позволяя вам чувствовать себя собой и перестать бороться против собственного мозга. Или можно принять другие таблетки – суицидальные. Третьего выбора нет. Все это приправлено жирными как мамаша читателя отсылками на “Матрицу”, фильм, сделанный двумя транс-женщинами.

Что тут можно было не вкурить? Конечно, это невероятное преувеличение и медикализация и фокус именно на отрицательных аспектах явления, но в этом же должен быть и поинт? Дисфория раздута до настолько очевидной пародии на саму себя, что даже самые запущенные цисы должны были понять происходящее. Это не могло быть совпадением.
