#+TITLE: Диалоговые механики Undertale

Продолжаем говорить про нарративный дизайн и диалоговые механики. На этот раз разберем диалоговые механики Undertale.

“Но Принцесса” — возразил никто, — “В Undertale и диалогов-то толком нет”.

Oh ye of little faith, воображаемый в душе собеседник.

Базовая механика диалога крайне проста и повторяет таковую в визуальных новеллах. Персонаж начинает говорить — текст начинает постепенно набираться в окошке — игрок может нажать Х, пропустить набор и показать все высказывание — если все высказывание показано на экране, игрок может нажать Х и перейти к следующему высказыванию.

Но Тоби Фокс сделал то, о чем я почему-то не слышу особо, когда люди обсуждают Undertale — он добавил персонажам голос.

Нет, я не имею ввиду звуковой эффект верещания, который у каждого персонажа свой. Это да, это есть. Но в том, как игрок взаимодействует с диалоговым полем, тоже есть голос!

Когда Альфис начинает восторженно рассказывать о своем любимом аниме, Mew Mew Kissy Cutie, это взаимодействие меняется. На этот раз, если ты нажимаешь X во время реплики, она не показывается целиком на экране, а пропускается. Но если игрок дослушивает ее до конца, она переходит к следующей реплике сама, не дожидаясь, пока игрок разрешит. Это создает очень четкое ощущение, что она тараторит без остановки, а игрок не может ее остановить.

Когда Меттатону нажимают кнопку, переключая его во вторую форму, он произносит “DID YOU. JUST FLIP. MY SWITCH”. Но между этими тремя фразами есть вынужденная пауза, первую секунду-полторы после появления игрок не может пропустить и перейти к следующей реплике. Это дает ощутимый вес фразе — это не просто одно разбитое на три группы предложение, а сдерживающий холодное возмущение, угрожающий робот, который постепенно оборачивается к игроку с прифигевшим взглядом.

Когда Санс в ресторане включает эджлорда и переходит на “Y O U D B E D E A D W H E R E Y O U S T A N D”, эту фразу пропустить вообще нельзя. Ты будешь ее слушать, побуквенно. Это добавляет в момент впечатления “резкая смена тона”.

Если придет в голову переигрывать — пообращайте внимание на такие детали. Диалоги выглядят пассивными, но в плане интерактивности с игроком они очень умно схореографированы. Да, часть “тона” в них задает звук, шрифт и саундтрек, но подача текста тоже очень сильно задает ритм, тон, скорость. В фандоме часто можно заметить, что все более-менее понимают и согласны, какой у разных персонажей голос, манера речи и акцент, хотя игра не озвучена даже!

Это, как по мне, один из ключевых моментов, которые делают персонажей настолько харизматичными. Разумеется, он не сработает сам по себе — музыка и звуковой дизайн тоже играют немалую роль — но это “секретный соус”, из-за которого персонажи такие живые, эмпатичные и запоминающиеся. “Клонов Undertale”, которые пытаются повторить успех, много, но они, я замечаю, копируют какие-то бросающиеся в глаза особенности, повороты, тропы. А Undertale силен такой проработкой деталей. Говоря с персонажами, ты будешь чувствовать, /как/ они говорят, но это почти “скрытая” фича, которую ты сознательно не заметишь, она оставит свой след исключительно на эмоциональном уровне. Который так просто не перескажешь, и который будет совершенно незаметен при просмотре игры “на ютубе”.

Причем этот прием намного мощнее обычной озвучки! Это не то что у Фокса не хватило денег на актеров, и он пытается сделать эрзац и передать интонации побочными средствами. Обычная актерская озвучка неинтерактивна — насколько бы профессиональным ни был актер, он в лучшем случае может выдать очень красивый и значимый, но статичный аудио-файл. “Озвучка” Фокса же зиждится на взаимодействии — персонажи по-разному реагируют на действия игрока на масштабах секунд. Игрок пассивно слушает? Или скипает по быстрому? Читает медленно, быстро? Перед ним критическая информация или легко пропускаемый филлер? Остановился на задуматься? При обычной озвучке диалога голос будет звучать одинаково, ты не сможешь передать ощущение “я изо всех сил пытаюсь ее заткнуть и вставить свое слово, но она не дает и игнорирует меня и верещит”.

Сила видеоигр как артформы — в интерактивности. Но интерактивность это не только для “геймплея” и “выбора сюжетных веток”. Правильно настроив взаимодействие с игроком, можно передать то, что “статические” артформы сделать не могут. Тоби Фокс сумел сделать интерактивной озвучку персонажей — и при этом очень дешево!

Таких мелких, не видных при чтении обзоров, но новых и мощных решений, в его играх много; возможно, я потом освещу еще несколько. Именно такие удачные решения — почему я считаю его гением, да.
