#+TITLE: Хвастовство 2025

Мемы в интернете, которые, да, находятся со мной в одной комнате, пытаются меня убедить в существовании древней норвежской традиции “йольского хвастовства”. Якобы на праздник Йоль – рождество, по-православному – принято хайпать свои достижения на будущий год, абсолютно не сдерживаясь в размахе. Уровень “я выиграю Одина в арм-рестлинг” – не цели, даже не вишлист, а дикий эскапистский фанфик про мэрисьюшную версию себя.

Мне не удалось найти этим словам подтверждения, но разве оккультным традициям нужно исторически корректное обоснование? Лекс рассказывал мне байку о знакомом, который поклонялся некоему “Косларейцу”, который точно так же туго гуглится – и у него, тем не менее, полностью успешно получилось сойти с ума.

Я обычно уважаю самоуничижительный юмор – все же говорят, “пиши, что знаешь”. Но, видимо, это не очень полезно для ментального здоровья. Как и шутки про самоубийство. Нужно себя любить, хвалить, поздравлять с достижениями и вообще источать позитив.

Так что эту традицию я возьму на новый год. Звучит здорово и полезно.

Итак, в 2025 году я:

- Подниму и опущу Солнце 365 раз

- Сделаю не менее 8 транс-переходов, с новыми механиками и повышенной сложностью в каждом

- Открою мир запутавшемуся в себе и рутине юноше, став для него Manic Pixie Dream Girl и запомнившись на всю жизнь

- Стану боссом организованной преступной группировки в Мар дель Плата

- Разрушу капитализм

- Получу Нобелевскую премию по психиатрии

- Похудею на 100кг

- Убью трех самых могущественных демонов в своей голове

- Магическим ритуалом нашлю понос на Дональда Трампа (на этот раз из правильного конца)

- Проведу модуль от начала до конца, с уровня 1 до уровня 20

- Таки трахну Калаверу

Всем спасибо за поддержку, друзья, без вас было бы в разы сложнее.

С Новым Годом!
