#+TITLE: Плохая астрономия и слова, слова

Джон астроном. Он очень классный астроном – он знает все про звезды, планеты, зодиаки, что там еще астрономы знают я не астрономолог. Если тебе нужно рассчитать расстояние до звезды или понять, как построить самолет, который работает на Марсе, или обработать данные с телескопа, чтобы найти обитаемые планеты – он тот самый парень, про которого ты будешь говорить “I know a guy”. А, и, ну, Джон живет в 2005, до того, как Плутон реклассифицировали как не планету.
Он пишет книгу про планеты в Солнечной Системе, сравнивая их параметры. В главе про размеры планет он пишет “самая маленькая планета в Солнечной Системе примерно 2400 километров диаметром”, имея ввиду Плутон.

Другой астроном, Джек, находит эту книгу в 2010. Он читает предложение “самая маленькая планета в Солнечной Системе примерно 2400 километров диаметром”. Джек знает, что Плутон не планета, так что он считает, что самая маленькая планета в Солнечной Системе – Меркурий, диаметром примерно 4900 километров. Он читает и думает “самая маленькая планета в Солнечной Системе диаметром 4900 километров. А Джон пишет, что самая маленькая планета в Солнечной Системе 2400 километров диаметром. Это прям очень большое расхождение! Он попытался измерить планету и ошибся почти в два раза! Очевидно, Джон ужасный астроном, раз даже не может посчитать размер планеты”.

Хотя Джон отличный астроном, так-то, он ошибся только в одной довольно неважной классификации. “Самая маленькая планета Меркурий, и Джон думает, что самая маленькая планета 2400 километров диаметром, значит Джон думает, что Меркурий 2400 километров диаметром” это ни капли не правильный логический вывод.

...окей, почему этот кажущийся банальным бит здесь написан? Как оказалось, для многих такое соображение не настолько очевидно, как для меня. После десяти раз, как я слышу в разговоре вывод такого рода, на одиннадцатый я лучше просто напишу типовой ответ в блоге и буду на него ссылаться потом. Приемник несет не меньшую ответственность за корректность информации, чем передатчик!
