#+TITLE: Факты и логика переоценены

[[https://sprott.physics.wisc.edu/pickover/esp.html][Небольшой эксперимент в агнотологии]] – пройдите его, потом читайте пост дальше (займет меньше минуты).

Я думаю, у людей, читающих этот блог, не составит затруднения понять, в чем заключается подвох, он очень простой и примитивный. Разумеется, у нас полно людей, которые верят в экстрасенсорику. Но идиотами я считаю не их. Это обыкновенный уровень заблуждения. Терпимый. Мы все порой совершаем ошибки такого рода. Идиотами я считаю [[https://sprott.physics.wisc.edu/pickover/esp4.html][скептиков, которые не верят]]. Избранные комментарии (перевод мой):

#+begin_quote
Я думаю ваш эксперимент работает, потому что большая часть людей выбирает карту слишком быстро и не дают компьютеру достаточно времени, чтобы выбрать другие карты случайно. Также приходит в голову мысль, что люди обычно кликают на ту сторону экрана, где расположена карта, так что компьютер может убрать некоторые карты из потенциальных выборов
#+end_quote

- Человек, который любит придумывать объяснения наблюдения сложнее самого наблюдения

#+begin_quote
Я попробовал эксперимент 50 раз подряд, и он дал мне правильный ответ каждый раз. Я повторю еще и посчитаю точно, но p-value уже достаточно низко, чтобы убедить меня, что это ничего не изменит. Я использовал генератор случайных чисел на калькуляторе, чтобы выбрать карту, и я нажимал на те же глаза каждый раз, и я ставил курсор над глазом до того, как нажал кнопку на калькуляторе, так что я был уверен, что сайт не использует движения курсора, чтобы предсказать карту. Я надел носок на камеру, чтобы сайт не следил за движениями глаз, и не издавал звуков, которые могли бы сказать, на какую карту я смотрю. Как это работает? HTML-код не пишет, откуда взялись изображения. Есть ли у вас другой исходный код, который я могу посмотреть?
#+end_quote

- Человек, который знает слово “p-value”, но не как измерять силу свидетельства; что такое “генератор случайных чисел”, но не как рандомизировать наблюдения; что такое “исходный код”, но не как работают программы.

#+begin_quote
Я прошел тест всего дважды, но как вы это делаете? Видимо что-то связанное с квадратиком с глазом, который был установлен на мой компьютер против моей воли и от которого я не могу избавиться. В таком случае, компьютер считывает наши движения глаз. Но как он это делает, если у меня нет веб-камеры? Или это чисто про математические вероятности? Мне любопытно
#+end_quote

- Человек, для которого объяснение “компьютер отслеживает мои движения глаз, хотя у меня нет веб-камеры” звучит разумнее, чем экстрасенсорика

#+begin_quote
У меня есть теория, как это работает. Одна карта слегка “темнее” и дает впечатление, что ниже, чем другие, в смысле 3D. Поэтому тебя тянет видеть именно эту карту
#+end_quote

#+begin_quote
Одна карта мерцает и подсознательно привлекает к себе внимание
#+end_quote

- Люди, которые тратят на порядок больше времени на формулировку гипотез, чем на проверку

#+begin_quote
Квантовая механика может обеспечить синхронность мысли и компьютера. Я предполагаю, что на квантовом уровне возможно предсказать карту, которую я выбрал до того, как я выбрал. Также возможно, что мои мозговые волны влияют на программы. Звучит натянуто, но мы уже знаем, что мозговые волны можно обнаруживать с помощью сверхпроводниковых квантовых интерферометров
#+end_quote

- Человек, который либо купил сверхпроводниковый квантовый интерферометр для своего домашнего ПК (менее тупой вариант) или считает, что экстрасенсорика это не экстрасенсорика, если она квантовая (более тупой)

#+begin_quote
Дорогой Клифф, ваша программа убрала правильную карту несколько раз, даже когда я говорил по-фински, когда называл карту. Не так много людей в англо-саксонском мире могут читать финно-угорский разум! Или, может, вы кельт? В любом случае, ваши навыки программирования впечатляют.
#+end_quote

- Человек с пытливым и креативным умом, который он решил направить на изучение Продвинутой Расовой Теории

#+begin_quote
Интересный эксперимент. Основанный на какой-то математической формуле, без сомнения. К сожалению, я не математик
#+end_quote

#+begin_quote
Ваш “тест экстрасенсорики” на самом деле математическая задачка. Та же, которой пользуются фокусники. Можно посчитать до почти 99.99, какую карту я выберу Билл
#+end_quote

- Люди, которые все еще недооценивают возможности математиков

#+begin_quote
Хорошая работа, мистер Пиковер! Ваш эксперимент поражает воображения, и я никогда не испытывал ничего подобного. Для начала, я попробовал эксперимент 49 раз. Из них, 7 раз я на самом деле смотрел на карту (не говоря вслух). В этих случаях моя карта была убрана из оставшихся. То есть в 100% случаев, когда я смотрела на карту, она была убрана, что само по себе восхитительно! 7 раз я смотрел на другую карту, при этом думая о той, которую выбрал. Из этих 7 раз, 7 раз была убрана карта, которую я выбрал. Но что замечательно это что в эти семь раз ОБЕ карты были убраны, и та, на которую я смотрел, и та, о которой я думал! 100% идеальный процент успеха. Так что я пошел на шаг дальше. 7 раз я выбрал 3 карты. Из этих 7 раз, НИ ОДНА из выбранных карт не появилась, что тоже замечательно /(дальше он постепенно доводит до 7 и удивляется, что были убраны все 7)/ Из этого делаю выводы либо: 1) Эксперимент использует программу для отслеживания глаз, на какую карту смотрит пользователь, но это не может быть правдой, потому что в семи попытках я смотрел на другую 2) Эксперимент использует истинное психическое программирование чтобы читать разумы субъектов, что есть восхитительное достижение технологии, если правда. Я восхищен. На краткий период времени. Можно понять, кто истинный гений за этим экспериментом. Спасибо, мистер Пиковер, что расширили мне ум, насколько бы ни на короткое время. Я апплодирую!
#+end_quote

- Человек, который знает, что “гипотезы надо проверять экспериментом”, но не очень понимает физический смысл этого заклинания и из-за этого наоборот предотвращает понимание

#+begin_quote
Ваш эксперимент восхитителен. Это наверняка очень сложный алгоритм!
#+end_quote

- Этого я просто обожаю

-----

Я не пытаюсь показать на тупых людей и смеяться. Мы все знаем, что люди бывают тупые. Я тоже часто бываю тупая. Этого не избежать, и это не новость. Я хочу показать несколько другое – что накидывать мемы науки, логики, рациональности – не помогает.

В наше время “скептицизм”, “рациональность”, “логика” – стали уже скорее сигналом, что ты принадлежишь к трибе людей, которые вот умные такие. Наука превратилась в литературный жанр, а не в метод. “Скептицизм” превратился из вполне разумной идеи, что нельзя брать вещи на веру, в группу “людей, которые не верят во всякую муть, в которую верят люди из противоположного жанра” – в магию, Бога, призраков – даже если чисто с точки зрения имеющегося на руках свидетельства, они берут на веру куда более глупые вещи. Люди запомнили ключевые слова, речевые конструкции и прочие тропы, связанные с философией эпохи Просвещения, но они воспринимают их как те же заклинания, что буквальные заклинания. “Это очень сильная магия” – фраза глупых людей из противоположного жанра, а “это очень сложный алгоритм” – фраза наша, научная. Хотя реальная объяснительная способность у них ровно одинаковая, и к ним надо относиться с одинаковым скептицизмом.

Логика это навык, ее надо учить. Наука это метод, ему надо тренироваться. Рациональность это, блин, на 70% жесткая математика и на 25% неочевидная психология. Тут надо книжки умные читать (или хотя бы блоги), а не кидать IQ в стенку, пока не получится. И если не изучили – так не пользуйтесь этим инструментом! Принимайте решения на эмоциях, на интуиции, на вайбах, по чужой рекомендации. Так реально лучше будет. Логика не всемогуща, это довольно узкоспециализированный инструмент, так-то. System 1 в человеческом мозге сильнее. Я вон тоже своим второстепенным цветом маны – красным – пользуюсь, когда знаю, что текущая проблема выходит за пределы моей компетентности с инструментами, которые у меня лежат в синем. Это не постыдно. Да, это инструмент противоположной трибы, но это вопрос социального сигналирования, а не принятия решений.

#+begin_quote
*Врезка на полях*

Королева Даннинга-Крюгера на почве “логики” – несомненно Айн Рэнд и все ее интеллектуальное наследие. “Объективизм”, твою мать. Мы тут самые объективные на районе. Настолько, что аж в название написали. Ошибка всех остальных в том, что они слишком субъективны. Если только включить логические отделы мозга, ты будешь один из нас. Никто на политическом компасе не совершает больше примитивных логических ошибок, чем ее последователи, и никто не постит больше мемов по поводу того, насколько все остальные углы компаса просто не умеют в “базовую логику” и принимают свои решения “чисто на эмоциях”, не то, что эти интеллектуальные гиганты. Хотя они себя логически загоняют в угол.
#+end_quote

И уж что точно делать не надо – это длинные логические цепочки, на основе которых вы получаете точные выводы. Это вот прям /очень/ узкоспециализированный инструмент. Человеческие мозги так не умеют нативно. Нужно быть очень продвинутым в этой области человеком, чтобы хотя бы понять, когда это может в теории сработать, а когда не может. Я видела полностью логически корректные обоснования существования Бога и несуществования Бога. Что капитализм хорошо и что капитализм плохо. Философы в шутку выдают логические цепочки уровня “начать с 2+2=4 и вывести из этого оптимальную тактику игры за Инвокера в DOTA”, но я видела и не такие разрывы контекстов на серьезных щах от серьезных людей.

Проблема с мышлением по Законам в том, что если ты неправильно понял Закон – хана тебе. Логическое умозаключение, в котором допущена хотя бы одна мелкая ошибка, полностью 100% бесполезно. Логика гарантирует, что если ты все сделаешь 100% правильно, ты получишь 100% верные выводы. Но если ты сделаешь все на 99.9% правильно, ты проснешься в ванне со льдом без почки.

Даже top dog математики не делают /выводы/ на основе доказательств. Доказательства это /последний шаг/, после того, как ты убедился в математических выводах на основе других соображений. Вот вам Генри “Последний Универсалист“ Пуанкаре:

#+begin_quote
“... I left Caen, where I was living, to go on a geological excursion under the auspices of the School of Mines. The incidents of the travel made me forget my mathematical work. Having reached Coutances, we entered an omnibus to go to some place or other. At the moment when I put my foot on the step, the idea came to me, without anything in my former thoughts seeming to have paved the way for it, that the transformations I had used to define the Fuchsian functions were identical with those of non-Euclidean geometry. I did not verify the idea; I should not have had time, as upon taking my seat in the omnibus, I went on with a conversation already commenced, but I felt a perfect certainty. On my return to Caen, for convenience sake, I verified the result at my leisure.”
#+end_quote

А вот Сриниваса “Матемагик” Рамануджан:

#+begin_quote
While asleep, I had an unusual experience. There was a red screen formed by flowing blood, as it were. I was observing it. Suddenly a hand began to write on the screen. I became all attention. That hand wrote a number of elliptic integrals. They stuck to my mind. As soon as I woke up, I committed them to writing.
#+end_quote

99% процентов работы выполняется нечеткой интуицией и мистическими видениями. Остальные 1% – уже логически обосновываются постфактум. Это не ошибка. Так работают мозги.

Лучшее, что здесь можно сделать – это хотя бы не класть яйца в одну корзину. Мышление по Хаосу неточно, но устойчиво. Сделай свой логический аргумент, и считай его одним из многих, не решающим. Логика говорит одно, слова эксперта другое, моя трудно определенная интуиция третье. Чтобы все твои источники решения оказались неправы одновременно – это нужен критический провал. Если ты пытаешься получить ответ на вопрос да-или-нет, и ты комбинируешь 100 независимых соображений, каждое из которых может оказаться правильным с вероятностью 60% – едва ли лучше, чем бросок монетки! – итоговый результат будет верен с вероятностью 98%. Мудрость толпы в твоей голове, йо. Опасайся только common source bias.
