#+TITLE: Гомосексуальная идентичность


Удивительно, насколько много людей задаются вопросом, считаешься ли ты геем, если трахнул членодевку. Ну то есть, не то чтобы удивительно, это понятно, но...

Гомосексуальность как идентичность это вообще довольно недавнее явление, ставшее ответом на систематическое угнетение (примерно по той же логике, по которой современные категории расы стали результатом рабства). Единственная причина, почему мы в принципе считаем гомосексуальность свойством человека, частью его сущности, его социальным кругом – потому что гомосексуалов в эту идентичность загнали насильно. И теперь они эту надуманную категорию интернализировали, as humans do.

Эта категория была бы непонятна, например, древним римлянам. У них толком не было и слова, которым можно было бы обозначить гомосексуального /человека/. Секс между двумя парнями это что-то, что могло кому-то нравиться больше, кому-то меньше, кому-то совсем нет; вокруг этого конечно же были свои не очень прогрессивные социальные нормы (в частности вокруг активности vs пассивности) – но частью идентичности это никогда не было, один акт не зашкваривал человека как что-то онтологически отдельное, равно как и отказ от однополых отношений не считался чем-то априорным.

Вопрос, делает ли какое-то конкретное действие тебя гомосексуалом, римлянину бы в голову не пришел, потому что для него это неестественная категория. Если ему объяснить ситуацию, реакция будет скорее всего недоуменная. Сам придумал термин, сам не можешь понять, что он значит, а потом сам по этому поводу страдаешь? Хватит играть в 3Д-латрункули против собственного мозга, найди реальную проблему и парься по поводу нее.

Принимать или не принимать /идентичность/ – вопрос того, какие вайбы угнетаемого существа, придуманные в прошлом веке, тебе больше нравятся. Я вот Принцесса, например, монархический угнетатель и даже не спорьте. Какие /реальные/ вопросы, а не бесполезные [[https://www.principiadiscordia.com/book/56.php][сетки]], можно задать по поводу секса с членодевкой?

Будет ли тебе она сексуально привлекательна, если ты гетеросексуал? Зачеркни последнюю часть – нравится или нет? Если не нравится член, ок, никаких проблем, многим, там, волосы в зоне бикини не нравятся, это не повод провозглашать себя каким-то суперстрейтом. Если нравится девушка, но не нравится член – вокруг этого можно работать, у всех есть недостатки, если бы я сильно парилась по поводу лишних частей тела на партнерах, я бы девственности никогда не лишилась. Если даже после полного перехода не нравится, потому что Y-хромосома, могу лишь порекомендовать ей сделать тест на кариотип – вдруг синдром де ля Шапеля? Не давай такой мелочи лишить себя любви!

Попадешь ли ты под зонтик ЛГБТ-угнетения, попав в эту надуманную категорию? Легитимный вопрос, многие все еще держатся за эту сетку. Будут ли тебя остальные считать гомосексуалистом на базе этого, изменится ли к тебе отношение? От окружения зависит, на зоне конечно об этом не говори. Но это инструментальный вопрос – к себе-то отношение точно не меняй, незачем.

Что еще зависит от того, считается ли это гомосексуальностью? Почему этот вопрос должен беспокоить?
