#+TITLE: Здравоохранение на рынке

Когда появился Uber, в США уже были такси и сервисы доставки. Они знали, что чтобы победить в конкурентной гонке, им надо... предложить услугу лучше, по цене ниже, так же рынок работает?

Ну, в целом, да. Они предложили что водителям, что клиентам цены значительно ниже рыночной и крайне выгодные предложения, работая сильно в убыток. Они теряли деньги, но стартового капитала и инвестиций от тех, кто видит возможность заработать, хватало. Такси, которым надо было таки зарабатывать деньги, работать в плюс - просто не могли соревноваться с практически халявой.

В 2023 Uber начал получать первые доходы - после того, как такси в США практически исчезли и все конкуренты были вытолкнуты из рынка. Теперь, конечно, Uber мог и повышать цены, и снижать качество, и высасывать соки из водителей. Что водителям, что потребителям, была бы выгоднее старая система такси, но, увы, Uber и аналогичные ему gig economy сервисы остались единственным выбором. Рынок сработал на свою основную задачу - обеспечил, что у людей не останется выбора, кроме как получать худшие товары и услуги за большие деньги.

О чем это я?

Частная медицинская страховка в США появилась где-то в районе Великой Депрессии - я полагаю, потому что все больше людей не могли позволить себе лечение. Идея была достойная, система Blue Cross - каждый человек/работодатель платил 50 центов в месяц (примерно 10$ по нынешним), и в случае болезни получал 21 день гарантированного медицинского обслуживания. Эта система позже была расширена до Blue Shield и набирала все больше популярности, став “стандартным” предложением бенефитов от работодателя.

Это была отличная система, она действительно помогала людям позволить себе лечение, хорошо оптимизировала затраты и выгоды лечения. Что же пошло не так?

Я не знаю, какое именно событие спровоцировало последующие изменения. Ненадежные источники говорят - потому что люди в целом стали здоровее и богаче, становилось все больше смысла не пользоваться страховками, а просто напрямую платить больницам. Здравоохранение становилось слишком хорошим и доступным, иными словами. Рынок такого не терпит.

Надо было вытеснить с рынка здравоохранение не через страховки. Страховые компании начали работать вместе с больницами и устанавливать общую ценовую политику. Идея была, что страховые компании платят больницам немного больше, и в обмен на это больницы обязаны запрашивать значительно больше денег с тех, кто не застрахован.

Больше людей не могли позволить лечиться без страховки и вынуждены ее покупать, отчего цена и страховок, и незастрахованного лечения стали раздуваться. Не по каким-то материальным причинам - лечение не стало сложнее, лекарства не стали реже, люди не стали больнее - а просто потому что пузырь. Пациенты не могут лечиться, не подписав договор со страховой компанией - потому что цены абсурдны. Больницы не могут быть экономически выгодными, не подписав договор со страховой компанией - ведь почти все деньги в индустрии идут через них. Спрос на лечение крайне неэластичный, так что раздувать цены можно практически неограниченно. Это было экономически выгодное соглашение для всех, кроме пациентов и врачей.

Ну и, конечно, очень обидно, что многие американцы считают это нормальным развитием вещей, и что поездка на скорой помощи до больницы /должна/ стоить тысячу долларов, что машина и труд парамедиков столько и стоят, а страховые компании приходят на помощь и позволяют народу позволить себе эту дорогущую услугу.

Ведь не может же так быть - что самые крупные игроки на рынке просто впитывают в себя огромные деньги, не предлагая ничего взамен, просто за счет того, что они /имеют право/ решать за врачей и пациентов, когда они могут лечить и лечиться?

Врачи, к счастью, немного более осознанны по поводу ситуации, и в большинстве своем ненавидят то, что на вытаскивание палок из колес они тратят больше времени, чем на работу. Хотя возможно у меня просто скошенная выборка - я ведь читаю только врачей, достаточно умных, чтобы писать.

А, и где-то здесь затесались государственные регуляции. Они тоже приносят какой-то вред, конечно. Не знаю, зачем я их вспомнила, просто почему-то каждый раз, как я об этом думаю, появляются призраки капитализма и напоминают.

Да, да, конечно, капитализм ведет к инновациям. Сколько инноваций придумали эти страховые компании в своей попытке взять с людей денег, но при этом не лечить. Ногу сломишь в этих премиумах, копеях, предшествующих состояниях, вот, я слышала, даже ИИ применяют с этой целью. Чтобы люди не могли лечиться от того, что их убивает - но все равно платили. Рынок сработал на свою основную задачу.

Так, о чем это я? Я же здесь про геймдизайн хотела писать. Я хотела сказать, что Luigi's Mansion 3, который на свитч - классный. Одобряю.
