#+TITLE: Гейл должен требовать магический предмет каждый продолжительный отдых


Скромное предложение: Гейл в Baldur's Gate III должен съедать магическую шмотку каждый продолжительный отдых.

*** Суть проблемы

Для тех, кто не играл, поясняю обе системы. Кто играл, можно скипнуть следующие два абзаца.

Гейл – один из доступных компаньонов. Вскоре после того, как ты его наймешь, он скажет, что ему нужно высосать магию из сильной магической шмотки, иначе будет катастрофа. Игрок вынужден на месте пожертвовать какой-то из  шмоток, иначе Гейл начнет получать прогрессирующе сильные дебаффы, а через три дня взорвется и вызовет мгновенное поражение. Его отпускает только временно, потом он еще дважды просит шмотку. На третий раз он говорит, что даже это теперь не помогает, и надо искать более перманентное решение. В конце первой трети игры оно находится.

Продолжительный отдых это способ восстановить ресурсы. В любой момент игрок может вернуться в лагерь и лечь спать, что полностью вылечивает всю партию, восстанавливает потраченные заклинания и прочие ресурсы, которые игрок расходует в процессе битв. Это можно сделать когда угодно, но не сколько угодно – это расходует еду (40 или 80 единиц). Если еды недостаточно, можно устроить “частичный отдых”, который восстанавливает не все ресурсы, но тем не менее считается отдыхом с точки зрения сюжетных событий.

Обе системы мне не очень нравятся.

Гейл банально раздражает. Когда я впервые услышала просьбу, моя мысль была “ок, без проблем, у меня есть парочка никому не нужных +1 кинжалов”, но оказалось, что ему не все шмотки считаются, и нужно было пожертвовать по настоящему полезную. К следующему разу ты, конечно, заготавливаешь что-то, чего не жалко, но осадочек остается. Никто не любит этот аспект Гейла.

Система продолжительного отдыха численно находится в таком балансе, что де-факто не играет роли и отдыхать можно когда тебе удобно. Недавно на реддит запостили мем, где человек показал, как у него кончилась еда, и комментарии были вида “не знал, что такое возможно”. И я не могу за это судить разработчиков – численно отбалансить эту систему так, чтобы лимит был осмысленный, но не душащий, очень сложно. И лучше пусть он будет неосмысленный – потому что очень много “единичек” еды валяются на земле где попало и требуют муторного собирания, и если игра для нормального прохождения будет их требовать собирать, это будет тоже очень раздражать.

*** Предложение

Я предлагаю усреднить эти две системы, чтобы их недостатки компенсировали друг друга.

1) Сделать Гейла не-опциональным компаньоном. Убрать возможность его обойти и не нанимать.
2) Сделать так, чтобы Гейл просил магическую шмотку каждый длительный отдых, всю игру.
3) Сделать больше (все?) магические шмотки допустимыми для Гейла. Мое понимание, что тогда их во всей игре хватит, чтобы гипотетически можно было отдыхать после каждого боя, но если это не так – увеличить количество магических шмоток в мире.
4) Убрать еду как механику; теперь де-факто цена отдыха – одна шмотка. Бесплатные частичные отдыхи оставить.

*** Плюсы

***** Лимит на длительные отдыхи теперь чувствуется и работает как реальный лимит

В игре лимитированное и заранее известное количество магических шмоток, и разработчику делать предположение, сколько их будет у игрока в какой момент, проще, чем с едой. Шмотки более интересные и индивидуальные, чем еда, и игрок будет осознавать, что каждый отдых чего-то стоит, но при этом и душащим он не будет. А если игрок все же пытается отдыхать достаточно часто, чтобы лимит душил – игра будет реагировать очень постепенно.

Сначала игрок жертвует бесполезные дешевые шмотки, которые ничего не стоят. Когда они кончаются, приходится покупать новые у трейдеров – недорогие существуют, поэтому это невелика проблема, но игрок поймет, что лимитирован. И шмотки, в отличие от еды, не респавнятся – рано или поздно они все же кончатся, бесконечно фармить их нельзя. Или можно пойти по более интересному пути – больше исследовать мир, больше выполнять квестов, чтобы получать больше шмоток – что, конечно, то, что мы хотим от игры как таковой. Потом, если и этого не хватает, придется жертвовать настоящие полезные шмотки, и тогда месседж о том, что тебе надо играть лучше и держаться дольше между отдыхами, будет слышен четко. Ну и даже когда ты /совсем/ кончился, когда тебе нечего жертвовать, кроме своей любимой артефектной булавы, без которой жизнь не мила, это все еще не полный запрет на отдых, не резкий гамовер, от отказа кормить Гейла до геймовера у тебя еще три дня.

***** Более плавный фидбек на скилл игрока

Такой фидбек намного лучше мотивирует игрока играть хорошо и интересно. При текущей системе, ты можешь отдыхать сколько угодно, пока внезапно уже не можешь – твой фидбек это просто “ты сыграл слишком плохо, все, конец”. Представьте, насколько бы какой-нибудь XCOM стал менее интересен, если бы потеря солдат не делала тебя слабее и никак не влияла на дальнейшую игру, но после 15 смертей наступал внезапный геймовер?

Здесь же игрок чувствует разницу плавно. “можно давать любой мусор, которого у меня целый мешок”, “надо тратить деньги, чтобы кормить Гейла”, “придется пожертвовать потенциально полезным амулетом”, “придется пожертвовать очень важным и нужным артефактным копьем”, “Гейл уже на последнем издыхании, надо срочно обыскать каждую помойку в городе, вдруг кто что выкинул” – это все качественно по-разному воспринимающиеся уровни срочности. Глубина опыта!

***** Меньше первоначальной фрустрации

Никто не любит внезапной необходимости отдавать Гейлу что-то нужное. Но в новой системе, когда Гейл подходит с первой просьбой, ему можно отдать бесполезную шмотку, которую ты и так хотел продать. Можно дополнительно убедиться, что в начале игры лежит достаточно много +1 кинжалов, чтобы игроку всегда было можно отдать, что не жалко. А на более продолжительном масштабе, когда необходимость платить шмотками уже воспринимается как устоявшееся правило, оно не будет вызывать фрустрации. По той же причине, почему в свое время в World of Warcraft система “через несколько первых часов в день ты устаешь и получаешь штраф к опыту“ вызвала масштабные недовольства, а система “первые несколько часов в день ты энергичен и получаешь бонус к опыту” была принята без проблем, хотя они были математически эквивалентны. Так здесь заведено, и если ты таки отдал шмотку, которую жалко – ты сам виноват, тебя предупреждали.

***** Меньше фрустрации при нахождении бесполезного лута

Я регулярно попадала в ситуацию, когда я выполняю сложный квест или проникаю в защищенную сокровищницу и получаю в награду шмотку... Но она оказывается слабее тех, которые у меня есть, или просто бесполезна для моей конкретной партии, приходится просто продавать. Здесь же каждая новая шмотка – это один дополнительный отдых. Вполне ощутимый и сильный бонус. Шмотки становятся ограниченным на всю игру ресурсом, как мини-версия Mind Player Tadpoles – их найти всегда приятно. И если тебе потребовался один отдых на вычистку данжа, и ты получил с него две шмотки – это уже считай окупилось.

***** Магические шмотки становятся mutually fungible с бонусами “до отдыха”

Такие бонусы обычно представлены эликсирами, выпивание которых дает тебе бонус, длящийся до следующего отдыха. Сейчас такие умирают от стандартной проблемы расходников в RPG “я дошел до конца с полным рюкзаком зелий, потому что каждый раз думал что потребуется дальше”. Теперь же такие бонусы находятся на той же шкале, что шмотки – если какой-то набор эликсиров позволил тебе пройти в два раза больше боев между отдыхами, то это сэкономило тебе шмотку, что /чувствуется/. Интересные стратегические выборы!

***** Поощряет менять компаньонов, а не оставаться с одной закостенелой пати всю игру

Каждый дополнительный компаньон – это дополнительный мешок со слотами заклинаний и прочими ресурсами, который может помочь дольше продержаться между отдыхами. Сейчас это не стоит своей мороки, но в новой системе от этого есть польза, и игра будет более разнообразной. И если уж ты используешь всех компаньонов, то почему бы не задуматься о том, какие лучше подходят для какого боя? Интересные стратегические выборы!

***** Легче адаптация к хардкорному уровню сложности

В список изменений для высокого уровня сложности добавить “теперь Гейл намного более привередлив к шмоткам и ест только хорошие и редкие” ← одна строчка решает проблему, которую в старой системе Ларианы решить не смогли.

***** Убирает сюжетную странность

Гейл требует три шмотки в течение первых 5 часов акта. На третью он говорит, что она уже почти не утоляет голод, и надо очень быстро искать новый способ его кормить. В течение следующих 40 часов он ничего не просит. Только потом его стабилизируют. Как-то тайминг не сходится! В новой системе не так, он просит шмотки стабильно раз в день и не стабилизируется никогда, что намного менее парадоксально.

*** Минусы

- Обязательный к употреблению компаньон в каком-то смысле нарушает принцип свободы для RPG?
- Гейл теперь еще больше раздражающе уберважная мерисьюха, на которой весь мир клином сошелся, чем он был до этого?
- Надо как-то исправлять перекос баланса в сторону менее зависимых от ресурсов классов типа Плута?

Что думаете?
