#+TITLE: Хорошие новости – ты не рыба

Мне сказали, что икота – это атавизм, доставшийся нам от рыб, что, мол, наш организм пытается ритмично двигать жабрами, и это выражается в виде икоты. И поэтому если хочется прекратить икоту, надо просто мысленно напомнить себе, что ты не рыба.

Звучит довольно тупо, да?

Работает. С тех пор, как я это узнала, я каждый раз, как начинаю икать, мысленно произношу фразу – “I am not a fish” – и икота мгновенно прекращается.

Звучит как тупая шутка, и я бы сама не поверила, если бы услышала. Но оно работает. Когда на меня нападала икота, никакие федоты и задерживания дыханий не помогали – а теперь я просто произношу одну фразу в голове, и как рукой снимает.

Попробовала на других подданных Солнечной Империи – они тоже говорят, что работает.

/Почему это работает?/ Просто для эффекта плацебо слишком мощно, а буквально что твой мозг на основе фразы, что ты не рыба, вспоминает, что ему больше не нужно двигать жабрами, это какое-то слишком магическое объяснение.

Я буду проводить эксперименты – говорить разные фразы на разных этапах икоты, и попробую понять, как оно работает. Приглашаю всех читающих, когда нападет икота, попробовать на себе и отрепортить – работает на вас или нет?
