#+TITLE: Таинственная культура спидранов

Я смутно понимаю текущую культуру спидранов.

Идея классная — показать мастерство игры и знание ее механик, чтобы максимально оптимизироваться. Спидраны, которые ее показывают — классные. Но топовые спидраны ничего общего не имеют с мастерством и пониманием игры.

Вот я сыграла в Forgotten City. Интересная, запутанная игра с множеством нюансов. Если бы мне поставили задачу ее проспидранить, это было бы довольно интересной задачей. В каком порядке оптимальнее всего проходить квесты? Оптимальнее ли брать на старте пистолет — ибо это сэкономит много времени с ассассином — или увеличенную скорость — ибо это чуть-чуть ускорит передвижение по миру в целом? Как можно ужать максимум событий в один день, чтобы минимизировать число ресетов? Надо ли проходить храм Артемиды или время, которое сэкономит золотой лук, того не стоит? Сколько минимум надо набрать голосов, чтобы избрали того, кого ты хочешь, и какие из этих голосов быстрее всего набрать? Я была бы очень рада увидеть, как кто-то находит решения всех этих вопросов в совокупности. Это было бы крайне интересно.

Открываю топовый спидран. Не, nevermind, Он просто с самого начала клипается сквозь стену в финальную локацию и пропускает всю игру. Такого спидрана Forgotten City, который реально показал мне то, что я хотела — понимание механик и умение их оптимизировать — я не нашла сходу.

Окей, ты воспользовался техническим решением, чтобы скипнуть всю игру и подарить себе победу, и что с того? С тем же успехом мог отредактировать файл сохранения или воспользоваться консольными командами. Я хочу видеть мастерство игры, а не клипание сквозь стену. Если бы авторы Alpha Go решили задачу написать ИИ, который выигрывает в го, путем подкупа текущего чемпиона, чтобы он сдался на первый ход, это будет прям достижение в ИИ и машинном интеллекте? “Мы технически выиграли, никто не говорил, что так нельзя!”

Тот факт, что такие спидраны смотрят, показывает, что интерес есть. Но я лично — совсем не понимаю такого подхода. И ведь если я когда-нибудь захочу сделать свой спидран, я буду сражаться не с мастер-геймерами, а с хакерами.
