#+TITLE: Terraforming mars это сингл-плеерная игра

Меня однажды подбили меня сыграть в Terraforming Mars. Это была одна из худших настолок, в которые я играла, и я играла в +мафию+ Монополию!

В игре нет [[https://www.gamedeveloper.com/design/what-is-yomi][йоми]], что есть единственный фактор, который делает соревновательные мультиплеерные игры интересными.

Игроки очень мало взаимодействуют. Обычно они каждый занимаются своими делами, пытаясь выжать максимум победных очков из имеющихся ресурсов. Им плевать, что делают остальные. Есть, конечно, исключения, есть betting on the commons, но в целом ты получаешь очень маленькое преимущество от знания, что делают другие игроки, в чем их план, что они думают. К середине игры мы даже перестали прятать карты в руках – не то чтобы знание чужих карт тебе чем-то поможет. По сравнению с покером, Старкрафтом, мафией, или даже камень-ножницы-бумагой, где если ты можешь читать мысли другого игрока, ты никогда не проиграешь. И именно попытка это распознать создает фан.

В Terraforming Mars, по сути, все игроки играют в сингл-плеерную игру и соревнуются в том, кто делает это лучше. Как сингл-плеерная игра она неплоха, может она была бы лучше, если убрать остальных игроков.
