#+TITLE: What is a woman

“What is a Woman” Мэтта Волша это... фильм.

Поначалу он просто тупил и творил херню, и я хотела написать этот пост как ревью на комедию. Но потом пошло откровенное /зло/ и прямая /ложь/.

(цитаты не совсем точные, ибо я вырезаю лишнее и суммаризирую)

В начале он задает вопрос — что такое женщина? Я не понимаю, давай найдем правду, где бы они ни была!

Почему он поднял такой вопрос? Потому что в наше время полно этих ваших трансгендеров, которые утверждают, что между полами нет никаких биологических различий и что мальчика можно воспитать как девочку и наоборот, и это ни на что не влияет (мы же это говорим, да?). Завершается интро вопросом — может ли быть, что у меня четыре дочери и мне придется платить за четыре свадьбы? Да, это самое важное, что его беспокоит.

Он играет роль человека, который искренне не знает ответа на вопрос и просто спрашивает. Его первый диалог был с психотерапевтом, который потоком льет на него ривилы уровня “да, у девочек могут быть члены, и если ты этого не понимаешь, то ты динозавр”. Потом идут диалоги с самыми разными про-транс людьми — профессорами в университетах, врачами и со случайными прохожими.

#+begin_quote

— Могу ли я быть женщиной? Мне нравятся ароматические свечи, и я смотрел Sex and the City.
— Да, ты можешь быть женщиной!

#+end_quote
#+begin_quote

— Что такое женщина?
— Женщина любит быть красивой и думает о себе как о деликатном существе...

#+end_quote
#+begin_quote

— Насколько рано ребенок может понять, что у него не тот гендер?
— О, очень рано, с первых лет!
— Встречали ли вы ребенка четырех лет, который верит в Санта-Клауса?
— Конечно, таких полно.
— Видимо, у детей не очень хорошее понимание реальности, ибо мы знаем, что Санты нет.
— Для ребенка он есть, и это самое важное!

#+end_quote
Тут начинается рефрен — для сторонников “гендерной идеологии” правда не важна, и они считают, что ее нет и есть только восприятие.
#+begin_quote

— Что если я скажу, что вы не существуете?
— Значит, для тебя мы не существуем.
— Но я существую — я с вами разговариваю.
— А ты уверен? (хихикает)

#+end_quote
#+begin_quote

— Вы продолжаете говорить слово “правда”. Я нахожу это грубым и уничижительным. Если вы продолжите говорить о правде, мне придется завершить это интервью.

#+end_quote
#+begin_quote

— Женщина это тот, кто определяется как женщина.
— Вы знаете, что такое “круговое определение”?
— Да, знаю.
— Вас ничего не смущает?
— Что такое?
— Вы можете определить слово “женщина”, не используя слово “женщина”?
— (пять секунд тупежа в пространство и выдавливания обрывков слов)

#+end_quote
#+begin_quote

— Почему вы спрашиваете меня, кто такая женщина? Я мужчина. Только женщина может знать, кто такая женщина!
— Вы кот?
— (четыре секунды паузы) Я сделал чудовищную ошибку! (Зойдбергит с экрана)

#+end_quote
Потом вопрос “что такое женщина” отходит на задний план. Вместо этого просто начинают говорить о трансах. И о транс-мужчинах тоже, да. Поиск определения на паузе.
Берет интервью у женщины-легкоатлетки. По ее словам, с тех пор, как транс-женщины начали соревноваться в женском спорте, она не выиграла ни одного соревнования! Ее мечты разрушены! Всегда выигрывают мужчины, притворяющиеся женщинами. Ей очень обидно — она всю жизнь тренировалась, а тут приходит хрен с горы, который вчера в спорт пришел, и выигрывает ее, только потому что транс. В спринте. Возьмите на заметку: трансы офигенны, переход позволяет тебе бегать быстрее, чем тренировавшиеся всю жизнь атлеты!
Следующий эпизод — расистский. Он приезжает в Африку и подходит к племени негров, живущих в соломенных халупах. Во время этого эпизода они постоянно отмахиваются от мух — просто случайная деталь. Начинает с ними разговаривать. Они ему объясняют — есть два гендера, палочка и дырочка. И к каждому закреплены строгие гендерные роли — мужчины делают одни профессии, женщины делают другие. На вопросы типа “может ли мужчина выполнять роль женщины, если захочет” или “может ли человек, родившийся с членом, быть женщиной” — негры поднимают на смех.
Он возвращается в Америку с выводом — “гендерная идеология” это чисто западный феномен, другие страны (метафорой для “стран, отличных от Америки” являются примитивные африканские племена) о нем не знают. Явно это не что-то естественное — это придумано и продвигается. Кем? Нет, он не намекает на евреев, что удивительно. Но он начинает исследование.
Ему показывают книжку, которая обозначена как “для детей от 10 лет”. Он открывает ее — боже, там говорится про половой акт! Он в шоке. Он спрашивает — что за хрень? Кто это продвигает? В головы наших детей это вбивают? Что это за зло творится?
Ему отвечают — Кинси и Мани.
Кинси поставил себе целью разрушить “Judeo-Christian values” (да, они использовали это словосочетание неиронично). Он поставил тезис, что все в жизни ради секса, и ради этого проводил сексуальные эксперименты над детьми. А исследования сексуальности взрослых он проводил на заключенных за сексуальные преступления — а потом расширил на всю Америку, что делает его исследования нелегитимными.
Мани. У него была идея, что дети рождаются без гендера, и их можно воспитать и как девочку, и как мальчика, эквивалентно. Он провел эксперимент, в котором родившегося мальчиком ребенка медицинским образом переделывают в девочку и воспитывают как девочку. Он от этого зарабатывает тонну психологических проблем, разумеется. Ругает, что неправильный пол сломал ему жизнь. Потом он пытается сделать детранзишн, но не успевает — умирает от самоубийства. Мани проигнорировал этот результат, записал в свою работу, что ребенку было норм, и провозгласил эксперимент успешным. По мнению лирического героя, это доказывает, что идеология, что твой гендер может не соответствовать твоему телу, и ты от этого будешь испытывать какую-то там дисфорию — ложна, и менять пол нельзя, потому что тогда будут самоубийства от несоответствия пола. Занятно.
Начиная с этого момента он про самоидентификацию забывает — он переходит к метафоре “не в том теле”. Переход — это смена тела.
(мне лично такая метафора категорически не нравилась, потому что я сильно пошла на психическое улучшение уже после социального перехода — еще до того, как в моем теле вообще стало что-то меняться — так что дело явно не только в теле, но уж в такие тонкости мы не можем ожидать углубления, да)
Следующий герой — бородатый мужчина с максимально, преувеличенно феминным голосом. Рассказывает, что она биологическая женщина (я не трансфоб), которая притворяется мужиком с помощью гормонов и операций, что археологи будущего откопают и поймут, что она женщина (да, именно так), но она никогда не станет мужиком (я не трансфоб), а эти тупые трансы не могут услышать и принять правду, что твой пол определяется при рождении и сменить его нельзя (я говорила уже, что я не трансфоб?).
(те, кто к этому моменту обратили внимание, что на мужских гормонах голос, в общем-то, ломается, и вот таким утонченно женственным он быть никак не может — плюсик в карму)
Какие у вас были операции? О, у меня их было аж 17. У меня были куча побочных эффектов! Сердечные приступы! Эмболизмы! Инфекции! Я вынуждена до конца жизни принимать антибиотики, чтобы выжить. Долго она еще не протянет. На этом моменте она начинает рыдать — у меня три ребенка! Неужели с ними сделают то же самое злые врачи? Я не хочу их терять! О горе!
Упоминаются исследования, что после операции почти все трансы совершают самоубийство. Говорят о девочке, которой начали давать гормоны, и через два года нашли остеопороз, вот что делают ваши гормоны! Нет, буквально, так и сказали. Могли бы добавить, что вот еще одна начала переход и потом на лестнице споткнулась и сломала ногу — но это бы уже было совсем комедийно.
Поднимается вопрос — почему об исследованиях Кинси и Мани никто не знает? Почему мне пришлось аж в Африку ехать, чтобы об этом узнать? Кто скрывает правду?
Big Pharma. На каждом ребенке, которого им удается убедить, что он транс, они зарабатывают 1.3 миллиона долларов! Один из препаратов, которые они насильно дают детям, используется для кастрации педофилов — к детям относятся как к педофилам.
На этом этапе все про-транс люди, с которыми он берет интервью, даже перестают его опровергать. Они просто говорят — ваши слова оскорбительны и унизительны, мы не хотим больше с вами разговаривать.
(периодически появляется Джордан Питерсон и душнит про определения, но это ничем не отличается от обычных перформансов Джордана Питерсона, здесь ничего нового не придумано)
Он связывается с человеком, сидящим с Канадской тюрьме. По его словам, ему однажды позвонили врачи и сказали, что будут насильно кормить его дочь гормонами. Он начал протестовать и случайно назвал ее не теми местоимениями. Его за это отправили в тюрьму. Он должен был заподозрить, что что-то не так, уже раньше! В его школе один ученик определяется как кот и разговаривает исключительно через мяукания, и учителям запрещено ему перечить или пытаться разговаривать с ним как с человеком, потому что их за это отправят в тюрьму. Интересно, Big Pharma уже зарабатывает на операциях по превращению в кота?
На этом моменте лирический герой шокирован. В темном подвале он подходит к пробковой доске с прикрепленными фотографиями и тянущимся от места к месту ниточками — да, реально, они буквально использовали эту символику — и вопрошает, что с этим делать. Он клянется разрушить этот заговор!
Он пишет книгу Johnny the Walrus. Да, это реальная книга, можно найти прочитать. Синопсис все передает:
#+begin_quote

Johnny is a little boy with a big imagination. One day he pretends to be a big scary dinosaur, the next day he's a knight in shining armor or a playful puppy. But when the internet people find out Johnny likes to make-believe, he's forced to make a decision between the little boy he is and the things he pretends to be — and he's not allowed to change his mind.

#+end_quote
Там ребенка насильно трансят в моржа, да. Он читает книгу своим друзьям-неграм в Африке, они угорают. Какие тупые западники!
Он едет в Теннесси, обосновывая это тем, что он Теннессиец в теле Вирджинианца (без этого между шатами ездить нельзя?). Там он приходит на конференцию. Он сразу же жалуется, что его свободу речи ограничили, заставив надеть “намордник” — медицинскую маску — я клянусь, он так и сказал. Там он по-быстрому зачитывает манифесто — он будет бороться с гендерной идеологией и спасать детей!
Титры.
Такие дела. Многие вещи, которые я тут описала, выглядят комичными и преувеличенными — но нет, все это на серьезных щщах, аж Питерсона пригласили. Я надеюсь, никого не удивит, что наш мальчик Илон “цисгендер это слур и неприемлем на Хвиттере, также я free speech absolutist” Маск этот фильм одобрил?
Если в голове людей такая картина, как работает трансгендерность... уф.

----------

То был пересказ, теперь конкретно тыкаю пальцем, почему все это плохо.
#+begin_quote

Потому что в наше время полно этих ваших трансгендеров, которые утверждают, что между полами нет никаких биологических различий и что мальчика можно воспитать как девочку и наоборот, и это ни на что не влияет

#+end_quote
Мы утверждаем ровно наоборот! От воспитания человека не в том поле идут огромные проблемы, и о биологических различиях между полами мы как раз очень сильно паримся.
#+begin_quote

может ли быть, что у меня четыре дочери и мне придется платить за четыре свадьбы

#+end_quote
Это могла быть off-шутка, но с учетом всего остального... это довольно патриархальное заявление, да.
#+begin_quote

Его первый диалог был с психотерапевтом, который потоком льет на него ривилы уровня “да, у девочек могут быть члены, и если ты этого не понимаешь, то ты динозавр”.

#+end_quote
В мире нет ни одного человека, который при разговоре с буквально Волшем начал бы делать свой поинт так. Это как давать Папе Римскому почитать /r/atheism
#+begin_quote

— Могу ли я быть женщиной? Мне нравятся ароматические свечи, и я смотрел Sex and the City.
— Да, ты можешь быть женщиной!

#+end_quote
#+begin_quote

— Что такое женщина?
— Женщина любит быть красивой и думает о себе как о деликатном существе...
Ни один человек, который воспринимает гендер как что-то серьезное, так не скажет, much less реальный врач по теме.

#+end_quote
#+begin_quote

— Насколько рано ребенок может понять, что у него не тот гендер?
— О, очень рано, с первых лет!
— Встречали ли вы ребенка четырех лет, который верит в Санта-Клауса?
— Конечно, таких полно.
— Видимо, у детей не очень хорошее понимание реальности, ибо мы знаем, что Санты нет.
— Для ребенка он есть, и это самое важное!

#+end_quote
#+begin_quote

Тут начинается рефрен — для сторонников “гендерной идеологии” правда не важна, и они считают, что ее нет и есть только восприятие.

#+end_quote
Многие праваки делают такой аргумент — из того, что самоопределение важно, они заключают, что мы считаем, что все, во что ты веришь есть правда и объективной реальности нет и ты можешь говорить что угодно, и что твои слова перебивают биологические факты. Конечно, это не так.
Если трансдевушка говорит, что она, допустим, девушка, она не пытается ни в чем обмануть. Она не пытается сказать вам, что у нее XY хромосомы или что она может забеременеть. Наоборот, мы как раз максимально паримся по поводу подлежащей за всем этим объективной реальностью, она для нас максимально важна. Просто мы включаем в наше понимание этой правды то, что пол\гендер, что биологический, что социальный, более сложный, чем кажется на поверхности — мы как раз подходим ближе к правде, которая, как всегда, сложнее, чем слова, и мы приводим терминологию ближе к этой правде.
#+begin_quote

— Женщина это тот, кто определяется как женщина.
— Вы знаете, что такое “круговое определение”?
— Да, знаю.
— Вас ничего не смущает?
— Что такое?
— Вы можете определить слово “женщина”, не используя слово “женщина”?
— (пять секунд тупежа в пространство и выдавливания обрывков слов)

#+end_quote
Помимо того, что настоящий профессор из института так тупить бы не стал, тут есть две проблемы.
1) “Женщина это тот, кто определяется как женщина” это не кольцевое определение. Потому что первое слово говорит о явлении, а второе о слове. Если бы это было записано на строгом языке программирования, а не на естественном с кучей неформальностей, то второе слово “женщина” было бы в кавычках. Сравните: Василий это тот, у кого в паспорте написано “Василий”. Вполне нормальное определение — если у тебя в паспорте написано “Василий”, то ты Василий, иначе ты не Василий, ничего кольцевого тут нет. И из этого не следует, что ты можешь определяться как угодно — если вы из этого перейдете к “Жираф это тот, у кого в паспорте написано “Жираф””, то это будет подмена понятий между “Жираф” как имя и “жираф” как животное.
2) Это не определение вообще. Это указатель. Если меня кто-то спросит, что такое апельсин, я могу протянуть ему апельсин и сказать “апельсин это то, что у меня сейчас в руке”. Он посмотрит мне в руку, поймет, о чем идет речь, и это будет вполне валидный способ объяснить ему, что такое апельсин. Но это не значит, что апельсин определен как “то, что у меня сейчас в руке”.
Слова, ребят! Слова работают не так, как вы думаете!
#+begin_quote

Берет интервью у женщины-легкоатлетки. По ее словам, с тех пор, как транс-женщины начали соревноваться в женском спорте, она не выиграла ни одного соревнования! Ее мечты разрушены! Всегда выигрывают мужчины, притворяющиеся женщинами. Ей очень обидно — она всю жизнь тренировалась, а тут приходит хрен с горы, который вчера в спорт пришел, и выигрывает ее, только потому что транс. В спринте.

#+end_quote
Преимущества у мужчин над женщинами в спринте есть, мужчины бегают почти на 10% быстрее, да. Я не уверена, насколько эта статистика распространится на транс-женщин, но даже если полностью — то этого преимущества, конечно, недостаточно, чтобы случайный транс с горы стал массивно побеждать над тренировавшимися всю жизнь профессиональными атлетами. Мне не удалось найти сравнительную статистику по поводу показателей трансженщин и цисженщин, но если бы они настолько радикально доминировали, мы бы об этом знали.
#+begin_quote

Следующий эпизод — расистский. Он приезжает в Африку и подходит к племени негров, живущих в соломенных халупах. Во время этого эпизода они постоянно отмахиваются от мух — просто случайная деталь. Начинает с ними разговаривать. Они ему объясняют — есть два гендера, палочка и дырочка. И к каждому закреплены строгие гендерные роли — мужчины делают одни профессии, женщины делают другие. На вопросы типа “может ли мужчина выполнять роль женщины, если захочет” или “может ли человек, родившийся с членом, быть женщиной” — негры поднимают на смех.

#+end_quote
Он возвращается в Америку с выводом — “гендерная идеология” это чисто западный феномен, другие страны (метафорой для “стран, отличных от Америки” являются примитивные африканские племена) о нем не знают. Явно это не что-то естественное — это придумано и продвигается. Кем? Нет, он не намекает на евреев, что удивительно. Но он начинает исследование.
Конечно, примитивное племя не будет знать тонкостей. Но оно также будет ржать над фразой “чем быстрее вы движетесь, тем медленнее для вас идет время” — но это не значит, что теория относительности это западный феномен, который кем-то там продвигается. И в не-западных культурах, да, гендеры бывают куда сложнее. Попробуте зайти на Grindr и погуглить все из десятков гендеров, которые там есть на выбор — большинство из них не то чтобы западные.
#+begin_quote

Кинси поставил себе целью разрушить “Judeo-Christian values” (да, они использовали это словосочетание неиронично). Он поставил тезис, что все в жизни ради секса, и ради этого проводил сексуальные эксперименты над детьми. А исследования сексуальности взрослых он проводил на заключенных за сексуальные преступления — а потом расширил на всю Америку, что делает его исследования нелегитимными.

#+end_quote
Здесь лирический герой не сказал никакой прямой лжи, но через умолчания и преувеличения рассказал не ту историю. Читайте про Кинси на вики.
#+begin_quote

Мани. У него была идея, что дети рождаются без гендера, и их можно воспитать и как девочку, и как мальчика, эквивалентно. Он провел эксперимент, в котором родившегося мальчиком ребенка медицинским образом переделывают в девочку и воспитывают как девочку. Он от этого зарабатывает тонну психологических проблем, разумеется. Ругает, что неправильный пол сломал ему жизнь. Потом он пытается сделать детранзишн, но не успевает — умирает от самоубийства. Мани проигнорировал этот результат, записал в свою работу, что ребенку было норм, и провозгласил эксперимент успешным. По мнению лирического героя, это доказывает, что идеология, что твой гендер может не соответствовать твоему телу, и ты от этого будешь испытывать какую-то там дисфорию — ложна, и менять пол нельзя, потому что тогда будут самоубийства от несоответствия пола. Занятно.

#+end_quote
Лирический герой принимает это за доказательство, что “гендерная идеология” неправильна. Хотя, на самом деле, эксперименты Мани, будь они двести раз неэтичные, показывают как раз обратное — несоответствие между ментальным и физическим\социальным полом бывает, оно вызывает психические проблемы вплоть до смерти, и воспитать человека не в том поле это ужасная идея.
#+begin_quote

Следующий герой — бородатый мужчина с максимально, преувеличенно феминным голосом. Рассказывает, что она биологическая женщина (я не трансфоб), которая притворяется мужиком с помощью гормонов и операций, что археологи будущего откопают и поймут, что она женщина (да, именно так), но она никогда не станет мужиком (я не трансфоб), а эти тупые трансы не могут услышать и принять правду, что твой пол определяется при рождении и сменить его нельзя (я говорила уже, что я не трансфоб?).

#+end_quote
Какие у вас были операции? О, у меня их было аж 17. У меня были куча побочных эффектов! Сердечные приступы! Эмболизмы! Инфекции! Я вынуждена до конца жизни принимать антибиотики, чтобы выжить. Долго она еще не протянет. На этом моменте она начинает рыдать — у меня три ребенка! Неужели с ними сделают то же самое злые врачи? Я не хочу их терять! О горе!
Чувак явно не AFAB, которого долбили гормонами — от этого его голос бы сломался; не то чтобы он стал бы совсем мужским, до полной маскулинизации обычно надо тренироваться, но таким утонченно-женственным он быть не может. “Притворяется мужиком”, “пол сменить нельзя”, “не можете понять правду” — ну, тот же рефрен, о котором я уже высказалась. 17 операций — это какой-то перебор, он мог удалить себе три пары сисек и сделать по одному члену на каждый гендер, и все равно столько бы не набралось. Все перечисленные им побочные эффекты при аффирмативных операциях замечены не были, кроме инфекций. Инфекции, да, бывают, как они бывают и при любой операции, как, например, при удалении вросшего ногтя, и они вполне лечатся, я даже не знаю, чтобы когда-то была такая ситуация, когда антибиотики пришлось бы принимать всю жизнь. Процент сожалений по поводу таких опреаций очень низкий, все довольны даже если появляются осложнения.
Ну и самое главное — никто не делает операции насильно. Есть, конечно, схемы с медицинскими туризмами и черными рынками, но конкретно в США, где происходит действие фильма, операции получить крайне сложно даже тем, кому они нужны, люди обследуются годами, подписывают кучу consent forms, и им отказывают, если есть мельчайшее подозрение, что это не самое лучшее решение. И детям они, конечно, не делаются.
Ну а по поводу археологов... Археологи не тупые, и у них намного больше техник и инструментов, чем штангенциркуль. Они занимаются наукой. Много случаев, когда они успешно определяли, что скелет принадлежит трансу. И скелеты не определяются однозначно как мужские и женские — там есть куча вероятностных критериев, ни один из которых не является определяющим.
#+begin_quote

Упоминаются исследования, что после операции почти все трансы совершают самоубийство.

#+end_quote
Трансы совершают самоубийство очень часто, да — но до перехода. После перехода (не обязательно операции) суицидальность падает резко.
#+begin_quote

. Говорят о девочке, которой начали давать гормоны, и через два года нашли остеопороз, вот что делают ваши гормоны! Нет, буквально, так и сказали. Могли бы добавить, что вот еще одна начала переход и потом на лестнице споткнулась и сломала ногу — но это бы уже было совсем комедийно

#+end_quote
Тут даже иронизировать лень.
#+begin_quote

Поднимается вопрос — почему об исследованиях Кинси и Мани никто не знает? Почему мне пришлось аж в Африку ехать, чтобы об этом узнать? Кто скрывает правду?

#+end_quote
Big Pharma. На каждом ребенке, которого им удается убедить, что он транс, они зарабатывают 1.3 миллиона долларов! Один из препаратов, которые они насильно дают детям, используется для кастрации педофилов — к детям относятся как к педофилам.
1.3 миллиона — это почти столько, сколько средний американец зарабатывает за всю жизнь. Чтобы они могли столько заработать, нужно чтобы /все/ деньги, которые заработал человек, шли исключительно на гендерно-аффирмативные вмешательства, и чтобы они шли напрямую в карман фарме, без необходимости тратить их на реальных врачей и медикаменты. Они даже не попытались сделать числа похожими на правду.
(нет, правительство не добавляет туда, никто тебе вагинопластику не оплатит)
#+begin_quote

Он связывается с человеком, сидящим с Канадской тюрьме. По его словам, ему однажды позвонили врачи и сказали, что будут насильно кормить его дочь гормонами. Он начал протестовать и случайно назвал ее не теми местоимениями. Его за это отправили в тюрьму. Он должен был заподозрить, что что-то не так, уже раньше! В его школе один ученик определяется как кот и разговаривает исключительно через мяукания, и учителям запрещено ему перечить или пытаться разговаривать с ним как с человеком, потому что их за это отправят в тюрьму. Интересно, Big Pharma уже зарабатывает на операциях по превращению в кота?

#+end_quote
Такого не происходит и никогда не происходило. Никто не делает гендерно-аффирмативные процедуры на детях и никого никогда не сажали за неправильные местоимения или за непринятие ученика как кота.
#+begin_quote

Он пишет книгу Johnny the Walrus. Да, это реальная книга, можно найти прочитать. Синопсис все передает:

#+end_quote
#+begin_quote

Johnny is a little boy with a big imagination. One day he pretends to be a big scary dinosaur, the next day he's a knight in shining armor or a playful puppy. But when the internet people find out Johnny likes to make-believe, he's forced to make a decision between the little boy he is and the things he pretends to be — and he's not allowed to change his mind.

#+end_quote
Никто не трансит детей насильно.
#+begin_quote

Он едет в Теннесси, обосновывая это тем, что он Теннессиец в теле Вирджинианца (без этого между шатами ездить нельзя?). Там он приходит на конференцию. Он сразу же жалуется, что его сободу речи ограничили, заставив надеть “намордник” — медицинскую маску — я клянусь, он так и сказал. Там он по-быстрому зачитывает манифесто — он будет бороться с гендерной идеологией и спасать детей!

#+end_quote
Ну это не ложь, это просто кринж.
Но насколько много людей воспримут за чистую монету?
