#+TITLE: Террористы аравийского полуострова

/[[https://l.dm.am/Comments.aspx?contentId=13053&contentType=9][Первоначально запощено на dm.am в рамках литературного конкурса.]]/

#+BEGIN_VERSE
НАТ. – БАГДАД – ПОЛДЕНЬ

Жара, смог. Дорога с редкими машинами. На лавке возле дороги сидит МАРЬЯМ (17) в плотном черном никабе. Рядом сидит ОМАР (20).

МАРЬЯМ (поет)
Моя умма, рассвет начался!
Победа как никогда близка!
Исламское государство поднялось кровью праведных!..

Омар резко закрывает ей рот ладонью и оглядывается. Прохожих рядом нет.

ОМАР
Тихо! С чего тебе в голову взбрело такое петь?! Только беду накличешь.

Марьям убирает ладонь Омара с лица, встает, делает шаг вперед от Омара.

МАРЬЯМ (оглядываясь на Омара)
Было бы интересно встретить настоящего террориста...

ОМАР
Дура! Это ужасные, подлые создания, которые только убьют тебя, коль под руку попадешься. Никакой праведный не будет видеть их как что-то, кроме грязи под ботинком.

МАРЬЯМ
Но они интересные. Сильные, смелые, решительные мужчины.

ОМАР
Ты хорошо себя чувствуешь на жаре, Марьям? Сколько на тебе слоев одежды?

МАРЬЯМ
Да

ОМАР (обеспокоенно)
Марьям?

Марьям делает пару шатающихся шагов вперед и выходит на дорогу. Омар встает со скамейки, неудачно пытается схватить Марьям за одежду. Марьям спотыкается, падает лицом на дорогу, лежит неподвижно.

Омар смотрит и видит, что на Марьям несется белая спортивная машина. Омар рвется стащить Марьям с пути, но явно слаб и не успеет.

Вид на холм на противоположной стороне дороги от Омара. С холма на большой скорости съезжает старая, ржавая, залатанная строительным скотчем машина. Врезается в белую машину поперек, перевернув набок и сбив ее с дороги на обочину в последний момент, едва избегая удара о Марьям и Омара.

Ржавая машина останавливается возле Марьям. Из машины выходит АХМЕД (28). Красивый, высокий мужчина, экстравагантный бродяга, с небрежно намотанным головным платком, спутанными волосами и бородкой, в поношеной многослойной одежде с множеством карманов и фенечек. Дерзкая, расслабленная улыбка. Машина за спиной Ахмеда разваливается на части.

Ахмед наклоняется к Марьям, отталкивая Омара. Стаскивает на обочину. Проверяет ее пульс, прикладывает ладонь ко лбу.

ОМАР
Ты кто такой?!

АХМЕД
Дышит. Перегрелась и упала в обморок.

Ахмед протягивает ладонь к Омару.

АХМЕД
Нож!

ОМАР
Что ты хочешь?..

Ахмед достает складной нож из кармана Омара, раскрывает и прикладывает к шее Марьям.

ОМАР (кричит)
Нет!

Ахмед разрезает воротник никаба, потом распарывает никаб дальше и стягивает его с Марьям. Из лежащей на боку белой машины выкарабкивается СААД (40), смотрит на Ахмеда и Марьям, звонит по телефону. Ахмед распарывает одежду дальше.

ОМАР
Что ты творишь, окаянный! Сокрой аурат! Ни стыда ни совести!

Ахмед замечает Саада

АХМЕД (Омару)
Найди тень и тащи ее туда.

Омар бросается к Марьям. Ахмед оставляет полуобнаженную Марьям на обочине, идет к Сааду.

АХМЕД (разводя руки)
Руль для тех, кого Аллах не направляет, да?

СААД (бросая трубку)
Ты кто такой вообще?

АХМЕД
Я инструмент Аллаха, не иначе!..

Ахмед приподнимает ладонь и смотрит в небо, потом опускает взгляд на Саада.

АХМЕД (прод.)
Как еще объяснить, почему я оказался в нужное время и нужном месте, чтобы спасти прекрасную даму?

СААД
Я бы свернул. А ты мою машину разбил, оборванец. Обдер бы тебя как липку, да ты не выглядишь, будто у тебя есть чего отбирать!

Ахмед вытягивает палец и прикладывает к губам Саада.

АХМЕД
Не шуми. Лучше смотри сюда. Твоя машина не так уж и разбита. Она почти альтернативно цела. Ездить будет только лучше. Вмятина улучшает аэродинамику, сечешь? Берись тут, вот, одну руку сюда, одну сюда.

Саад с недоуменным видом исполняет приказания.

АХМЕД
На счет три толкаем вместе. Раз. Два. ТРИ!

Ахмед и Саад толкают машину, и она встает на колеса.

СААД
Заклинаю тебя Аллахом — говори правду, что ты здесь делаешь?

АХМЕД
Ну раз Аллахом!

Ахмед с хлопком складывает ладони перед грудью.

АХМЕД (прод.)
Я просто искал новую машину. Моя слишком подозрительно выглядит, ее проверят задолго до того, как сдетонирует бомба.

СААД
Ты еще смеешь шутки шутить, после клятвы?!

АХМЕД
Истинная правда.

Подъезжает машина полиции, из нее выходят ДВА ПОЛИЦЕЙСКИХ. Саад указывает пальцем на Ахмеда, и полицейские хватают его, один за каждое плечо.

ПОЛИЦЕСКИЙ 1
Создал аварию, машина без номеров.

ПОЛИЦЕЙСКИЙ 2
Имя, документы?

АХМЕД
Я забыл паспорт в другой машине.

Полицейский 1 достает из кармана Ахмеда пистолет.

ПОЛИЦЕЙСКИЙ 1
Конфискуем

Омар и Марьям подходят к Ахмеду и полицейским. Марьям прикрыта остатками никаба, опирается на плечо Омара.

МАРЬЯМ
Будьте с ним полегче, офицеры, он спас мне жизнь! Его надо благодарить, а не лапать!

Полицейские отпускают Ахмеда. Он трет плечо и подмигивает Марьям. Марьям кокетливо улыбается и подмигивает в ответ.

ПОЛИЦЕЙСКИЙ 2
Это не значит, что ты свободен.

ПОЛИЦЕЙСКИЙ 1 (осматривая пистолет)
Пистолет с барахолки. Одна пуля. Зачем такой вообще носить?

АХМЕД
Какой есть...

ПОЛИЦЕЙСКИЙ 2
А я тебя знаю! Только что дошло, откуда тебя помню.

Ахмед поднимает бровь.

ПОЛИЦЕЙСКИЙ 2
Насколько же ты опустился, Ахмед Скарабей! Ты худший террорист, о котором я слышал.

АХМЕД
Но ты обо мне слышал.

СААД
Так он правду говорил! Он хочет бомбу взорвать! У него в машине бомба!

Полицейские смотрят на обломки машины Ахмеда рядом.

АХМЕД (цокая языком)
Аллах Акбар!

Полицейские падают на землю ногами к машине и закрывают головы руками. Ахмед бежит к полицейской машине, садится в нее и отъезжает.

АХМЕД (выглядывая из окна)
Спасибо за тачку!

ПОЛИЦЕЙСКИЙ 1 (поднимая голову)
Так бомбы нет?

АХМЕД
Еще не установил! Но все равно спасибо!

Полицейские встают и бегут за машиной, но Ахмед уже разогнался. Полицейские понимают, что не догонят, и останавливаются.

Вид на лицо Марьям с блаженной улыбкой.
#+END_VERSE
