#+TITLE: Narrative design in Disco Elysium

Narrative design is not exactly my cup of tea, but I have some thoughts.

An RPG's dialogue system by itself limits what kinds of characters and stories you can work with. Let's take /Disco Elysium/. What can we say about their dialogue system?

1) Harry never acts on his own; his every word and action must be vetoed by the player. Foil: In /Witcher III/, the player chooses major dialogue junctions, and in between those Geralt can converse for as long as he wishes.
2) Replies that we choose are always “direct speech” — the specific words Harry is to say. Foil: In /Mass Effect/, the player chooses the general direction of the reply (“agree to the plan”, “explain the situation”), and the game expands this to a full speech.
3) There are no information in the reply that the character knows and the player doesn't. Foil: In /Baldur's Gate III/, a possible option might be “[Dwarf] I recognize this rock, it's a bovinomorphic coprolith”.
4) The “author's voice” telling us hard facts, and the “character voice” that is filtered through the protagonist's perception are clearly distinct. We learn most things from the latter — the author only speaks of trivialities that can't be misinterpreted. Foil: /Planescape: Torment/, where what the hero sees, what he intuits, what he introspects, and what he remembers from behind the veil of amnesia — all of that is just one author-voice block of text.

The game sticks to those axioms, sometimes twisting into logic pretzels in an attempt to not break the rules. Whenever the hero has to know something the player doesn't, the voices in his head tell us both that — and that feels like learning about the world and not like the hero started out with more information than us. In the notorious “I want to have fuck with you” scene, you only get one dialogue option, which seems basically the same as Geralt answering automatically. However, before that, the voices in your head play out a big ceremony about how you lose control of your libido, and apologize in advance for the stupid thing that's about to come out of your mouth. And you still have to explicitly click on the line, so it feels like it was /you/ who blurted it out in a brief lapse of self-control. This makes the phrase something between an establishing character moment and a relatable cringe attack that we all remember when we are trying to fall asleep. Foil: Commander Shepard keeps saying things you never intended to, and it's always annoying.

It's an excellent approach that hits the sweet spot between a purely freeform roleplay and a rigid premade character. Harry is by no means a blank protagonist, it's a specific person with a specific life, specific opinions, specific quirks, and specific skills. And yet he is still an RPG character that can be roleplayed as you want. The player settles down in his head, learns about his story and his demons and his unusual worldview, and yet he is still making the decisions, playing the role. The limits on roleplaying Harry are internally justified and heartfelt. Foil: the limitations on roleplaying Geralt are justified by the authors telling us what kind of person Geralt is.

There is never this dissonance between how you see the character and what the character does. People critique games like /Mass Effect/ for “in-head roleplaying” when in the actual game you just get to choose between paragon and renegade. This is not a problem in /Disco Elysium/. Despite the fact that you literally have to choose between different positions on the political compass!

People [[https://www.youtube.com/watch?v=cSmZcN7AgHQ][compare Disco Elysium to tabletop RPGs]] when they want to explain what they like so much about it, but I think they all miss the point. It's not about replicating the TTRPG experience. In TTRPGs you make your own character and roleplay them however you want, while the DM allows you to do whatever you want. Blank slate, sandbox. In /Disco Elysium/, this is not how it works. You are given a specific character and told to play as him. But you /play/ as him, and not just ride along as he does his thing. The character you get to play is, by himself, literary content, an interesting feature of the game that you don't need to invent yourself. But you still maintain the freedom of roleplaying.

This best-of-both-worlds solution is what makes Disco Elysium so narratively appealing. People praise the story, of course, but the story is not the point. Just the plot of the game, described as a sequence of events, isn't anything too special. Notice that in this analysis I haven't even said anything about the story yet! It doesn't really matter at this point, what world the game takes place in, who our character is, or what he does. The game's narrative is well-designed at the level of base game mechanics. Of course, you still need good script writers for this to work, but the innovation comes from the narrative designers.

--------–-----

However, not every protagonist can be played like that.

First off, the obvious: the hero needs to be an amnesiac. Either with a literal amnesia, like in /Planescape: Torment/, or an indirect one, like in /Vampire: The Masquerade — Bloodlines/. The game needs the player to not know anything about the world in advance, and this is the standard way to do it.

And because of that, the setting itself must be new. Planescape, Forgotten Realms, or World of Darkness are all settings that already have a media presence, and many players know a lot about them coming in. Those games can afford having different dialogue branches for different players. Newcomers can ask NPCs about the difference between a Gangrel and a Gargoyle, veterans can just skip. In /Disco Elysium/, we can't do that. We sit inside Harry's head and observe the inner machinations of his mind in real time, hitching on the ride as we both learn about the setting. If the game ever has a direct sequel, they'd need to either have a different mechanical structure of dialogues, or make it in a different part of the world; otherwise you wouldn't be able to make a game that is playable for both newbies and veterans.

Somewhat less obviously — the hero can't be wordy. Every reply must be short and to the point. Kim can afford vanting about problems in the precinct, Measurehead can rant on his racial theory, Ervart can emit flowery prose about how much he respects people with convictions. But Harry can't explain anything, can't recount, can't pepper his dialogue with superfluous pleasantries or long introductions. Compare Harry's replies in /Disco Elysium/ with The Nameless's replies in /Planescape: Torment/. Those characters display radically different levels of directness, quirkiness, and oh-so-randomsness; and the dialogues in both games would lose in quality if you swap them.

And the most difficult limitation to work with is that the player can't plan dialogues. We can't prepare a rhetorical trap and catch the opponent lying. We can't strategically reveal information to later use it. We can't subtly guide towards an idea before saying it outright. Harry is fully and fundamentally a vibe-based creature, controlled more by the ancient reptilian brain than by the neocortex. His investigation method is based on perfecting the Discordian art of making locally good decisions and seeing one step forward so well that you never even need to consider the global picture. Interestingly, Kim fully understands this. When the team needs to tell a newly minted widow that her husband died, Kim gives very specific and detailed instructions to Harry about what to say, and if Harry starts veering off the script, Kim subtly pushes him away and seizes the initiative. The fact that the authors managed to make a work of detective fiction under these limitations is astonishing. Harry is a ‘human can opener', manipulator and provocateur, even though he has not a drop of machiavellianism in his blood. And it looks completely natural.

(Notice that I still haven't said much about the story)

Knowing all this, I am curious — what would be some equally organic narrative mechanics for the opposite hero archetype? A rational strategist, well-versed in the lore, ready to break into rants. This is not a hypothetical question, by the way. I had a prototype of an RPG that had this kind of protagonist, but it kept not working out. Then I played /Disco Elysium/ and realized what exactly I couldn't get right! There are a lot of subtle minutiae to work on in mere dialogue mechanics.

I will ponder this puzzle some more.
