#+TITLE: Doomsday argument is hopeful

There's a well-known philosophical concept known as the Doomsday Argument. Here's Randall Munroe's simple take on it:

#+begin_quote
Humans will go extinct someday. Suppose that, after this happens, aliens somehow revive all humans who have ever lived. They line us up in order of birth and number us from 1 to N. Then they divide us divide them into three groups—the first 5%, the middle 90%, and the last 5%
Now imagine the aliens ask each human (who doesn't know how many people lived after their time), “Which group do you think you're in?”
Most of them probably wouldn't speak English, and those who did would probably have an awful lot of questions of their own. But if for some reason every human answered “I'm in the middle group”, 90% of them will (obviously) be right. This is true no matter how big N is.
Therefore, the argument goes, we should assume we're in the middle 90% of humans. Given that there have been a little over 100 billion humans so far, we should be able to assume with 95% probability that N is less than 2.2 trillion humans. If it's not, it means we're assuming we're in 5% of humans—and if all humans made that assumption, most of them would be wrong.
To put it more simply: Out of all people who will ever live, we should probably assume we're somewhere in the middle; after all, most people are.
If our population  [[http://www.un.org/esa/population/publications/longrange2/WorldPop2300final.pdf][levels out around 9 billion]], this suggests humans will probably go extinct in about 800 years, and not more than 16,000.
#+end_quote

And people don't seem to agree on it:

#+begin_quote
Almost everyone who hears this argument immediately sees something wrong with it.
The problem is, everyone thinks it's wrong for a different reason. And the more they study it, the more they tend to change their minds about what that reason is.
Since it was proposed in 1983, it's been the subject of tons of papers refuting it, and tons of papers refuting  /those/ papers. There's no consensus about the answer; it's like the  [[http://blog.xkcd.com/2008/09/09/the-goddamn-airplane-on-the-goddamn-treadmill/][airplane on a treadmill]] problem, but worse.
#+end_quote

But more notable to me is the utter pessimism surrounding the argument. Even its name implies DOOM, that we will all die out and that's bad. We have 800 years left, and it's terrible!

But let's look at it from another direction. The argument says that we are among the last in line (for a certain meaning of “last”). This doesn't mean that we will go extinct after that! We are the last humans who are to be born, doesn't mean we will die in 800 years. The argument is fully compatible with the idea that the last people will live a million years each.

And take note — the Doomsday timer depends on how many people there are in the future. 800 years is for if the current prognoses of Earth population keep being relevant. But the bigger the population grows, the closer is the Doomsday. If the current prognoses were telling us that the population would grow to 20 billion — the day is closer, and the argument is probabilistically stronger. The more people there are in the future, the closer the Doomsday, after which no more people will be born.

Yes, it's an argument towards that nothing much will change for the next 800 years, and then we all die.

But, probabilistically, it's a much stronger argument that very soon — not in 800 years, but way sooner — the population will grow abruptly, and then we stop dying.

Perhaps we should have called it The Singularity Argument?

I am sometimes optimistic.
