#+TITLE: Inexplicability of miracles is evidence against God
#+LANGUAGE: en
#+SUBSTACK: https://thesolarprincess.substack.com/p/inexplicability-of-miracles-is-evidence
#+DATE: <2026-08-31 Mon>

There's a [[https://benthams.substack.com/p/a-clash-of-titans-the-ethan-muse][discourse on substack about divine miracles]] these days, in particular about the [[https://en.wikipedia.org/wiki/Miracle_of_the_Sun][Fatima miracle]], and whether it proves God exists/Catholicism is true. Some try to rebut it on meta grounds, like pointing out comparably awesome miracles in favor of a /different/ religion. But the most popular line of attack is to try to find a naturalistic explanation for the miracle: to explain, scientifically, what actually happened there. The background assumption is that if there is no naturalistic explanation, then God exists. Even Scott Alexander, after [[https://www.astralcodexten.com/p/the-fatima-sun-miracle-much-more][his first failed attempt to find a non-theistic explanation]], got a bit spooked that hell might be real (though he later made a [[https://www.astralcodexten.com/p/waiting-for-the-miracle][second, more successful attempt]]).

This feels strange to me, because, given my priors, if we found a naturalistic explanation, that would /increase/ the probability of God's existence.

There's a naive worldview underlining this, a picture of the world where God's existence implies constant miracles and magic and wonder, while God's absence means a mechanistic clockwork universe where everything happens predictably as the math says. But that's not actually a /model/ that predicts observations which can be tested or updated via Bayes' theorem — it's a way to sort memes into one of two allegedly opposed literary genres: "science" and "religion." If you try to think probabilistically within that picture anyway, you get a degenerate model. God can do anything, and his motives are unknowable — so no observation counts against religion. But science is supposed to explain everything in existence, so any gap in our understanding counts against science.

In reality, neither of these is actually predicted by theism or naturalism. In the current naturalistic model of the universe, the world is just weird. [[https://johnsalvatier.org/blog/2017/reality-has-a-surprising-amount-of-detail][Reality contains a surprising amount of detail]]. It's full of unexplained mysteries, oddities, anomalies, remarkable coincidences, intentional hoaxes, and seeming paradoxes. Some of them eventually get explained (e.g., the Dyatlov Pass incident), some remain mysterious to this day (the Voynich manuscript). And it's not just because our knowledge of the laws is incomplete — many mysteries are pragmatically unsolvable, because too much time has passed and all the leads are lost to entropy. And even the leads we do have, we often hear through twenty rounds of the game of telephone. And that's even before we get to phenomena that are genuinely underexplored by science, but which we nonetheless presume to fit within a naturalistic worldview (e.g. we don't know exactly how schizophrenia works, but we assume there's /some/ mechanism there that doesn't contradict the laws of physics).

On the other hand, theism doesn't exactly /predict/ miracles like Fatima. There's a rich theological tradition around [[https://en.wikipedia.org/wiki/Divine_hiddenness][divine hiddenness]], and I've seen plenty of works of analytic philosophy that argue for why God would create a predictable universe that follows some physical law. Some solutions to the problem of evil likewise imply that God wouldn't just casually intervene for trifling reasons. Contrasting with this, the God of the Old Testament intervenes very overtly and unmistakably; if one were to live through those events, they would be foolish to disbelieve. I'm fine with either kind of God; they both seem a priori sensible. But if miracles like Fatima happen through divine intervention, breaking the laws of physics – then it implies that God follows the laws of physics most of the time, but occasionally, very rarely, for a handful of random people who happened to be in the right place at the right time, arranges a miracle that sits right at the edge of credibility. And on top of that, He isn't even doing something useful (Jesus at least healed the sick and fed the hungry) – he's just doing something anomalous that isn't interesting or significant in any way other than its anomalousness. This is absolutely not something I would expect to see if God exists. A hidden God, or a God who overtly intervenes only in very significant cases like the coming of Christ – that I could still believe, given sufficiently good arguments, or if an angel descended from the Heavens and told me about it. Let's say my subjective probability there is 1%. But the kind of cringe prankster fifth-grader God who would just do Fatima? I rule that out almost completely; 0.0000001%.

We definitely don't live in the Old Testament obvious-God world; miracles don't happen constantly and regularly; I have never once seen an angel. Either we live in a fully naturalistic universe, or we live in a world with a God who wouldn't do such dumbass miracles. In neither case did /the Fatima miracle specifically/ happen through direct divine intervention. It /definitely/ happened entirely in accordance with the laws of physics, even if those laws were created by God.

So when I hear that no scientist can explain some anomaly, I don't think "wow, that means God exists." I think "wow, the world really is very complex, and our ability to explain it is quite limited." The more Fatima-level anomalies I see, the more convinced I become that we're bad at explaining things, and that our naturalistic model is incomplete. My probability of God's existence doesn't change – instead, probability shifts from "the natural world is basically explainable, and every anomaly is a problem that needs to be accounted for" to "the natural world is basically unexplainable, and all anomalies can be just taken at face value."[fn::and, I guess, technically some of it also shifts to the prankster God who uses his divine powers exclusively to show up on toast and do Fatima and stuff, but that probability is negligible enough that it takes bytes and bytes of Bayesian evidence to move it by a fraction of a percent, so it doesn’t matter]

But there are also plenty of other things that theism /actually/ predicts better than naturalism. [[https://philopedia.org/arguments/fine-tuning-argument/][The fine-tuning of the universe]]. The [[https://en.wikipedia.org/wiki/Hard_problem_of_consciousness][hard problem of consciousness]]. "Why does the universe exist in the first place." There are some half-baked preliminary naturalistic answers to those, but no full consensus. I don't think that these problems are fundamentally insurmountable for naturalism – there are probably solutions that don't require God, you have probably already thought of some. But as far as the likelihood ratio goes, the existence of God would explain them directly and neatly. Of course God would fine-tune the universe so that life could exist in it! That sounds more like God than cartoons in the sky! Those problems being unresolved is evidence for God's existence. Not enough evidence to believe on that basis alone, and rapidly diminishing as we get closer to solving them, but non-zero.

So, to sum up. I read "no one can explain the Fatima miracle." I also know that the Fatima miracle has some kind of explanation that doesn’t require God. Since we can’t find it, that means we're really just dumb and bad at explaining things. That means that unexplained anomalies don‘t matter much, of course there’s going to be anomalies, our world-model downright /predicts/ that there’s a lot in the world that we can’t explain. This applies to anomalies that are /actually/ evidence for God's existence as well! So those don't matter much either. We don't know why the universe is fine-tuned – so what, there's a lot we don't know, we're monkeys with attitude. My belief in God /decreases/, because some of the evidence in favor of God becomes weaker.

And if I later hear that a naturalistic explanation has in fact been found, this update reverses. My belief in God goes back to where it was before I heard of the Fatima miracle – it goes *up*.

---

I'm writing this because I noticed an anomaly in my own thinking. For some reason, when I heard about the Fatima miracle, I felt that it meant atheism was winning. And when I later saw a naturalistic explanation I found satisfying, I felt that atheism had taken a hit. This intuition felt correct to me, even though it was strange and didn't match how everyone else was talking about the miracle. So I began untangling my intuition, to find out why it does what it does, to reflect on the computation that is happening under the hood, and determine whether it's actually correct or just a bug/cognitive bias. I concluded it's completely valid given my explicit priors.
