#+TITLE: Fallout: Equestria addiction arc

[[https://en.wikipedia.org/wiki/Fallout%3A_Equestria][Fallout: Equestria]] is extremely /viscreal/. I don't know how the author does it, but it makes you feel /everything/. Every time the protagonist is hit, you flinch. Every time the protagonist is scared, you jump in your seat. I don't know how it works. It's like some kind of subtle word magic is at action. As far as I can tell, it doesn't work on everyone — some are immune to the magic — and thus not everybody appreciates this particular aspect of the book's genius. But for me, it definitely worked.

Nothing exemplifies this better than Littlepip's struggle with addiction. Early in her journey, she finds some Party-time Mint-als ([[https://fallout.fandom.com/wiki/Mentats][mentats]]). True to the original games, they gave her a temporary boost in stats, but taking it too much might result in addiction, and your stats will actually be lowered while you're not under the drug's influence.

Initially, she takes the Mint-als occasionally to overcome some hard problems. It's very helpful, so she starts taking them more and more. Then she starts taking them just for fun, when no obstacle was actually present. Eventually she catches herself thinking how she just isn't herself when under the drug's influence, how only the drug makes her feel normal.

At some point, her friends stage an intervention and get her to a doctor, who cleans her system of the drug (that's how it works in Fallout). He warns her that while the chemical effects of the drug are gone, the psychological might remain, and that if she ever starts taking the drug again, the addiction might return.

After the procedure, Littlepip feels renewed, rejuvenated, remarkably clear-headed and happy. She initially mistakes it for some kind of high, but then she realizes that this is how she normally feels — that's what she was like before she started taking the Mint-als. All this time, she was a sluggish, brain-fogged, weakened, irritated mess, and she only felt a semblance of normality when under effects of the drug.

/And I felt all of that./

I felt highspirited whenever she took the drug. I felt down and sluggish whenever she was off the drug. Often I caught myself wishing she would take the pill already, and felt relieved when she actually did. I felt the brain fog — the final chapters before she went clean really did feel sluggish and slow, as if my brain wasn't working properly. The writing and the events felt irritating and uncomfortable — until she took the drugs again, that is. And when she went clean — I really did feel like a mountain was lifted off my shoulders. The universe felt beautiful again. My brain got working back up to speed. Only then I realized how slow and miserable I felt throughout the latest chapters — and how it only got worse and worse as Littlepip's addiction worsened. /I felt it all./

I don't know how well that reflects real-life addiction — I've never been addicted to any drug in my life. But if it works like that in reality, then I totally get what everybody's talking about and how addiction ruins you so thoroughly. If you or anyone you know are addicted, then I'm sorry.

Some time later Littlepip finds her stash of the drug and ponders whether to throw it away to not risk getting re-addicted, or to keep it in case she ever needs a boost in an emergency. That really felt like a dilemma. Lots of writers set up contrived moral dilemmas with one answer clearly marked with author's endorsement — but this one felt genuine.
