#+TITLE: Gale from Baldur’s Gate III should eat a magic item every long rest

I like neither the Gale's arcane hunger system nor the long rest system.

Arcane Hunger is just annoying. First time Gale asked me to eat an item, I was like “sure, no problem, I have some +1 daggers that I don't care about”, and then it turned out that not all magic items are eligible, and I need to sacrifice an actually useful thing. By the next time he came up I prepared a sacrificial bauble, of course, but I was still a bit salty. Nobody likes this aspect of Gale.

The long rest system is numerically at the spot where it doesn't really limit you in any way and you can rest whenever you want. Recently, a redditor posted showing him running out of food, and everyone was like “I didn't know that was even possible”. And I can't blame Larian — balancing this system so that the limit is real but not suffocating is really hard. And I can understand why they'd rather make in inconsequential — if playing the game required obsessively collecting every 1-sup fish head, it'd be supremely annoying.

**** The Proposal

Merge those two systems and have them negate each other's downsides.

1) Make Gale a non-optional follower. He can't be skipped and he can't be fired.
2) Make Gale ask for a magic item every long rest, for the entire game.
3) Make more (all?) magic items edible. As far as I can see, there are enough magic items in the world that you could comfortably long rest after every fight if you have all of them; if not, then add more edible items.
4) Remove camp supplies. Now the price of a long rest is one magic item. Don't remove “free” partial rests for advancing the story.

**** Upsides

****** The long rest limit is now a true strategic limit

There is a limited and known number of magic items in the world, and it's easy for the game designer to assume how many the player will have at any moment. Magic items are more notable and less fungible than foodstuffs, so the price of a long rest feels impactful, but not overwhelming. And if the player wants to rest often and stretch the limit, it will happen /gradually/.

At first, you sacrifice worthless baubles that have no other purpose to them. When they run out, you have to buy more items from traders; cheap items exist so this isn't much of a problem, but /you notice/. And unlike foodstuffs, magic items don't respawn, so you can't farm them forever. At this point you can go the interesting route — explore more, do more quests, search more dungeons so they can find more items, which is what we wanted you to do in the first place. If that's not enough, you might need to lose some potentially useful rings, and then actual gear, and at that point you'd know that you are in danger. And in the worst case scenario, there's three days from running out to game over, so that's still not a complete ban on long rests, you have time to think about how to dig yourself out of the ditch.

****** Less upfront frustration

Nobody likes that one moment when Gale starts asking for items and you need to part with something you like. But in this new system, the first time it happens you can give him a useless bauble that you planned to sell anyway. We can make extra sure that the player has enough worthless +1 daggers by that point in game to have something to give. And in the long run, when the price of a long rest is established as a rule, it won't feel frustrating — for much the same reason why, in World of Warcraft, the system “after the first few hours of playing each day you get a penalty to XP” was met with uproar, and the mathematically equivalent “for the first few hours of playing each day you get a bonus to XP” was accepted with no complaints. That's the rule of the game, a ring for a rest, and if you ever need to part with your favorite weapon, that's your fault and you had been warned.

****** Less frustration at finding useless loot

I regularly found myself in a sutiation where I complete a difficult quest or infiltrate a treasury or clear a dungeon, and my reward is a magic item... that is weaker than anything I have, or just straight up doesn't fit my specific party composition. And I have to sell it for boring gold. In the new system, every new item you find is /at least/ one more long rest you can take. Magic items become a gamewise-limited resource, like a mini version of a Mind Flayer Tadpole, and they are always exciting to find. And if you had to take one long rest to clear a dungeon and you looted two items from it — you would know it paid for itself.

****** Faster and smoother feedback

In the current system, you can take as many rests as you want until you suddenly can't. Running out of food is the only point of feedback you actually get. Imagine how much worse XCOM would be if losing soldiers meant nothing until at the 15th death you suddenly get a game over?

Here, you can feel how well you play, by how long you can last between rests. “I just dump useless trash straight into Gale's open mouth”, “I have to spend money to keep going”, “I have to part with a nice but not essential item”, “I have to lose my favorite legendary weapon”, and “I have three days to find something to save myself” are all qualitatively different experiences with different senses of urgency. Phenomenological depth!

****** Magic items become mutually fungible with consumables

Potions, elixirs, arrows, bombs, and scrolls suffer from the classic RPG problem of “I never use them until the last fight because I might need them in the future”. Now, consumables can be used to save on magic items! If those ten potions let you take on twice as many fights before you had to rest, then you essentially exchanged those potions for a (unique and named!) magic item, which /feels/ meaningful and makes it worth it to not hoard consumables.

****** Easier to adapt for hardcore difficulty

For Honor Mode difficulty you add the condition “now Gale is more picky and only eats stronger magic items”. Boom, this adds real strategic difficulty when increasing food cost from 40 to 80 didn't.

**** Downsides

- A non-optional companion might sort of violate freedom of choice in this kind of an RPG?
- Gale is now even more of an omni-important Mary Sue?
- Mostly-resourceless classes like Rogue might need a comparative nerf?

What do you think?
